#ifndef _NETCA_PKI_CONST_INLCUDE_H_
#define _NETCA_PKI_CONST_INLCUDE_H_

#ifdef __cplusplus
extern "C"
	{
#endif

#ifndef NETCADLLAPI

	#ifdef _WIN32
		#define NETCADLLAPI __stdcall
	#else
		#define NETCADLLAPI
	#endif

#endif

/*	错误码 */
/* 成功 */
#define NETCA_PKI_SUCCESS			1
/* 失败 */
#define NETCA_PKI_FAIL				0
/* 无效的参数 */
#define NETCA_PKI_INVALIDARG		-1
/* 无效的句柄 */
#define NETCA_PKI_INVALIDHANDLE		-2
/* 内存分配失败 */
#define NETCA_PKI_OUTOFMEMORY		-3
/* 输出缓冲区太小 */
#define NETCA_PKI_MOREDATA			-4
/* 密码错误 */
#define NETCA_PKI_PWD_ERROR			-5
/* 已经存在 */
#define NETCA_PKI_EXISIT			-6
/* 不存在 */
#define NETCA_PKI_NOTEXISIT			-7
/* 拒绝访问 */
#define NETCA_PKI_ACCESSDENIED		-8
/* 不支持 */
#define NETCA_PKI_UNSUPPORTED		-9
/* 未实现 */
#define NETCA_PKI_NOTIMPLEMENT		-10
/* 超时 */
#define NETCA_PKI_TIMEOUT			-11
/* 构造证书链失败 */
#define NETCA_PKI_BULID_CERTPATH_FAIL		-12
/* 验证证书链失败 */
#define NETCA_PKI_VERIFY_CERTPATH_FAIL		-13
/* 不在有效期内 */
#define NETCA_PKI_NOT_IN_VALIDITY			-14
/* CRL或OCSP不在有效期内 */
#define NETCA_PKI_REVOKEINFO_NOT_IN_VALIDITY	-15
/* 不符合安全环境的要求 */
#define NETCA_PKI_VIOLATE			-16
/* 没有装载UI的共享库 */
#define NETCA_PKI_NOUI			-17
/* 用户取消了操作 */
#define NETCA_PKI_USER_CANCEL		-18
/* 密码长度错误 */
#define NETCA_PKI_PWD_LENGTH_ERROR		-19
/* 密码格式错误 */
#define NETCA_PKI_PWD_FORMAT_ERROR		-20
/* 数据长度过大 */
#define NETCA_PKI_DATATOOLONG				-21
/* 密码没有被锁死 */
#define NETCA_PKI_PWD_NOTLOCK				-22
/* 加密证书没有匹配的加密密钥对 */
#define NETCA_PKI_ENC_KEYPAIR_NOTFOUND		-23
/* 签名证书没有匹配的密钥对 */
#define NETCA_PKI_SIGN_KEYPAIR_NOTFOUND		-24
/* 没有匹配的设备 */
#define NETCA_PKI_NOSUCHDEVICE				-25
/* 没有匹配的密钥对 */
#define NETCA_PKI_NOSUCHKEYPAIR				-26
/* 证书匹配表达式错误 */
#define NETCA_PKI_BADCERTMATCHEXPR			-27
/* 没有根证书 */
#define NETCA_PKI_NO_ROOTCERT				-28
/* 没有合适的作废信息 */
#define NETCA_PKI_NO_REVOKE_INFO			-29
/* 没有合适的CA作废信息 */
#define NETCA_PKI_NO_CA_REVOKE_INFO			-30

/* 应用密码错误 */
#define NETCA_PKI_APP_PWD_ERROR				0x10000


/* Hash算法 */
/* MD5算法 */
#define NETCA_PKI_ALGORITHM_MD5		0x1000
/* SHA1算法 */
#define NETCA_PKI_ALGORITHM_SHA1	0x2000
/* SHA224算法 */
#define NETCA_PKI_ALGORITHM_SHA224	0x3000
/* SHA256算法 */
#define NETCA_PKI_ALGORITHM_SHA256	0x4000
/* SHA384算法 */
#define NETCA_PKI_ALGORITHM_SHA384	0x5000
/* SHA512算法 */
#define NETCA_PKI_ALGORITHM_SHA512	0x6000
/* SM3算法 */
#define NETCA_PKI_ALGORITHM_SM3		0x7000


/* Mac算法 */
/* HMAC-MD5算法 */
#define NETCA_PKI_ALGORITHM_HMAC_MD5		0x20000
/* HMAC-SHA1算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA1		0x40000
/* HMAC-SHA224算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA224		0x60000
/* HMAC-SHA256算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA256		0x80000
/* HMAC-SHA384算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA384		0xA0000
/* HMAC-SHA512算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA512		0xC0000
/* SSL3使用MD5的Mac算法 */
#define NETCA_PKI_ALGORITHM_SSL3_MD5_MAC	0xE0000
/* HMAC-SM3算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SM3		0x100000
/* SSL3使用SHA1的Mac算法 */
#define NETCA_PKI_ALGORITHM_SSL3_SHA1_MAC	0x120000

/* 对称加密算法 */
/* ECB模式的DES算法 */
#define NETCA_PKI_ALGORITHM_DES_ECB			0x400000
/* CBC模式的DES算法 */
#define NETCA_PKI_ALGORITHM_DES_CBC			0x800000
/* ECB模式的3DES算法 */
#define NETCA_PKI_ALGORITHM_3DES_ECB		0xC00000
/* ECB模式的3DES算法 */
#define NETCA_PKI_ALGORITHM_3DES_CBC		0x1000000
/* CTR模式的3DES算法 */
#define NETCA_PKI_ALGORITHM_3DES_CTR		0x1400000
/* ARC4算法 */
#define NETCA_PKI_ALGORITHM_ARC4			0x1800000
/* ECB模式的RC2算法 */
#define NETCA_PKI_ALGORITHM_RC2_ECB			0x1C00000
/* CBC模式的RC2算法 */
#define NETCA_PKI_ALGORITHM_RC2_CBC			0x2000000
/* ECB模式的AES算法 */
#define NETCA_PKI_ALGORITHM_AES_ECB			0x2400000
/* CBC模式的AES算法 */
#define NETCA_PKI_ALGORITHM_AES_CBC			0x2800000
/* CTR模式的AES算法 */
#define NETCA_PKI_ALGORITHM_AES_CTR			0x2C00000
/* ECB模式的SSF33算法 */
#define NETCA_PKI_ALGORITHM_SSF33_ECB		0x3000000
/* CBC模式的SSF33算法 */
#define NETCA_PKI_ALGORITHM_SSF33_CBC		0x3400000
/* CTR模式的SSF33算法 */
#define NETCA_PKI_ALGORITHM_SSF33_CTR		0x3800000
/* ECB模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_ECB			0x3C00000
/* CBC模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_CBC			0x4000000
/* CTR模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_CTR			0x4400000
/* ECB模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SMS4_ECB		0x4800000
/* CBC模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SMS4_CBC		0x4C00000
/* CTR模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SMS4_CTR		0x5000000
/* ECB模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SM4_ECB			0x4800000
/* CBC模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SM4_CBC			0x4C00000
/* CTR模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SM4_CTR			0x5000000
/* ECB模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_ECB_MOD		0x5400000


/* 非对称算法 */
/* RSA算法 */
#define NETCA_PKI_ALGORITHM_RSA		1
/* DSA算法 */
#define NETCA_PKI_ALGORITHM_DSA		2
/* DH算法 */
#define NETCA_PKI_ALGORITHM_DH		3
/* ECC算法 */
#define NETCA_PKI_ALGORITHM_ECC		4
/* 只能用于OAEP的RSA算法 */
#define NETCA_PKI_ALGORITHM_RSA_ONLY_OAEP	0x11
/* 只能用于PSS的RSA算法 */
#define NETCA_PKI_ALGORITHM_RSA_ONLY_PSS	0x21
/* 只能用于ECDH的ECC算法 */
#define NETCA_PKI_ALGORITHM_ECC_ONLY_ECDH	0x14
/* 只能用于ECMQV的ECC算法 */
#define NETCA_PKI_ALGORITHM_ECC_ONLY_ECMQV	0x24





/* 密钥对生成算法 */
/* RSA算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_RSA		1
/* DSA算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_DSA		2
/* DH算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_DH		3
/* ECC算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_ECC		4

/* 非对称加密算法 */
/* PKCS#1 V1.5的RSA加密算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_V1_5_ENC		0x10
/* PKCS#1 OAEP的RSA加密算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_OAEP			0x20
/* 原始未填充的RSA加密算法 */
#define NETCA_PKI_ALGORITHM_RSA_RAW_ENC				0x30
/* SM2加密算法 */
#define NETCA_PKI_ALGORITHM_SM2_ENC					0x40
/* ECC的ECIES加密算法 */
#define NETCA_PKI_ALGORITHM_ECIES					0x50


/* 签名算法，只用于设备接口 */
/* PKCS#1 V1.5的RSA签名算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_V1_5_SIGN		0x100
/* PKCS#1 PSS的RSA签名算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_PSS			0x200
/* 原始未填充的RSA签名算法 */
#define NETCA_PKI_ALGORITHM_RSA_RAW_SIGN			0x300
/* DSA签名算法 */
#define NETCA_PKI_ALGORITHM_DSA_SIGN				0x400
/* ECDSA签名算法 */
#define NETCA_PKI_ALGORITHM_ECDSA_SIGN				0x800
/* SM2签名算法 */
#define NETCA_PKI_ALGORITHM_SM2_SIGN				0x1000


/* 签名算法，用于应用程序 */
/* MD5WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_MD5WITHRSA				1
/* SHA1WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA1WITHRSA				2
/* SHA224WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA224WITHRSA			3
/* SHA256WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA256WITHRSA			4
/* SHA384WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA384WITHRSA			5
/* SHA512WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA512WITHRSA			6
/* MD5WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_MD5WITHRSA_NOHASHID		7
/* SHA1WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA1WITHRSA_NOHASHID	8
/* SHA224WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA224WITHRSA_NOHASHID	9
/* SHA256WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA256WITHRSA_NOHASHID	10
/* SHA384WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA384WITHRSA_NOHASHID	11
/* SHA512WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA512WITHRSA_NOHASHID	12
/* DSAWithSHA1 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA1				13
/* DSAWithSHA224 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA224			14
/* DSAWithSHA256 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA256			15
/* ECDSAWithSHA1 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA1			16
/* ECDSAWithSHA224 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA224			17
/* ECDSAWithSHA256 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA256			18
/* ECDSAWithSHA384 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA384			19
/* ECDSAWithSHA512 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA512			20
/* SSLV3使用的RSA签名 */
#define NETCA_PKI_ALGORITHM_SSL_RSA					21
/* RSA PSS 签名 */
#define NETCA_PKI_ALGORITHM_RSA_PSS					22
/* ECDSAWithSM3 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSM3			23
/* SM3WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SM3WITHRSA_NOHASHID		24
/* SM3WithSM2 */
#define NETCA_PKI_ALGORITHM_SM3WITHSM2				25
/* SHA1WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA1WITHSM2				26
/* SH224WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA224WITHSM2			27
/* SH256WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA256WITHSM2			28
/* SH384WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA384WITHSM2			29
/* SH512WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA512WITHSM2			30
/* SM3WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SM3WITHRSA				31
/* PKCS#1 V1.5的RSA签名算法，只用于NetcaPKICryptoSignHash和NetcaPKICryptoVerifyHash */
#define NETCA_PKI_ALGORITHM_RSASSA_PKCS1_V1_5		32
/* 非标准的SM3WithSM2，不用Z的 */
#define NETCA_PKI_ALGORITHM_SJS_SM3WITHSM2			33

/* 密钥协商算法 */
/* DH */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_DH			0x10000000
/* MQV */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_MQV		0x20000000
/* ECDH */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_ECDH		0x30000000
/* ECMQV */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_ECMQV		0x40000000
/* SM2 */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_SM2		0x50000000



#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA1		1
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA224	2
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA256	3
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA384	4
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA512	5

/* PKCS#5的PBKDF1，不推荐使用 */
#define NETCA_PKI_KDF_ALGORITHM_PKCS5_PBKDF1	1
/* PKCS#5的PBKDF2 */
#define NETCA_PKI_KDF_ALGORITHM_PKCS5_PBKDF2	2
/* PKCS#12的KDF */
#define NETCA_PKI_KDF_ALGORITHM_PKCS12			3
/* DH的KDF */
#define NETCA_PKI_KDF_ALGORITHM_DH_RFC2631		4
/* SM2的KDF */
#define NETCA_PKI_KDF_ALGORITHM_ECC_ANSI_X9_63	5

/* 使用所有的UNCIDE字符，而不只是BMP */
#define NETCA_PKI_PKCS12_FLAG_USEALLUNICODE		1
/* 按照MS的方式进行截断 */
#define NETCA_PKI_PKCS12_FLAG_MSTRUN			2


/* 密码类型 */
/* 用户密码 */
#define NETCA_PKI_USER_PWD			1
/* 管理员密码 */
#define NETCA_PKI_SO_PWD			2
/* 应用密码 */
#define NETCA_PKI_APP_PWD_BASE		0x10000			


/* 不支持获取密码错误重试次数 */
#define NETCA_PKI_UNSUPPORTED_RETRY_NUMBER			-1


/* 密钥对类型 */
/* 加密密钥对 */
#define NETCA_PKI_KEYPAIRTYPE_ENCRYPT			1
/* 签名密钥对 */
#define NETCA_PKI_KEYPAIRTYPE_SIGNATURE			2
/* 密钥协商密钥对 */
#define NETCA_PKI_KEYPAIRTYPE_KEYAGREEMENT		3


/* ECC曲线类型 P192 */
#define NETCA_PKI_ECC_CURVE_P192			1

/* ECC曲线类型 P224 */
#define NETCA_PKI_ECC_CURVE_P224			2

/* ECC曲线类型 P256 */
#define NETCA_PKI_ECC_CURVE_P256			3

/* ECC曲线类型 P384 */
#define NETCA_PKI_ECC_CURVE_P384			4

/* ECC曲线类型 P521 */
#define NETCA_PKI_ECC_CURVE_P521			5

/* ECC曲线类型 WAPI规定的曲线 */
#define NETCA_PKI_ECC_CURVE_WAPI			6

/* ECC曲线类型 SM2推荐的曲线 */
#define NETCA_PKI_ECC_CURVE_SM2				7


/* 设备类型 */
/* 这个不是一个真正的设备类型，只是表示可以匹配任意的类型 */
#define NETCA_PKI_DEVICE_TYPE_ANY			-1
/* 内置的软件实现，不是一个真正的设备 */
#define NETCA_PKI_DEVICE_TYPE_BUILDIN_SOFTWARE		0
/* 明华EK-PK系列的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_EKPK		1
/* 明华版本2的EK-PKXC系列的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_EKPKXC_V2	2
/* 飞天epass3000 */
#define NETCA_PKI_DEVICE_TYPE_EPASS3000		3
/* 海泰的Key */
#define NETCA_PKI_DEVICE_TYPE_HAIKEY		4
/* 飞天epass3003 */
#define NETCA_PKI_DEVICE_TYPE_EPASS3003		5
/* 明华版本3的EK-PKXC系列的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_EKPKXC_V3		6
/* 明华文鼎创EKey */
#define NETCA_PKI_DEVICE_TYPE_MWESKEY	7
/* 微柏的Key */
#define NETCA_PKI_DEVICE_TYPE_WEEPAL 	8
/* 飞天502的卡 */
#define NETCA_PKI_DEVICE_TYPE_FT502 	9
/* 飞天SM2的Key */
#define NETCA_PKI_DEVICE_TYPE_FEITIAN_SM2 	10
/* 天翼税通上海普华COS */
#define NETCA_PKI_DEVICE_TYPE_ETAX		30
/* 天翼税通华为COS */
#define NETCA_PKI_DEVICE_TYPE_HWETAX		31
/* 南方基地ECC设备 */
#define NETCAPKI_DEVICE_TYPE_ECCEKEY_CISIP	32
/* 海泰的SM2的Key */
#define NETCA_PKI_DEVICE_TYPE_HAIKEY_SM2	33
/* UIM Key */
#define NETCA_PKI_DEVICE_TYPE_UIMKEY		34
/* HD Micro SD Key */
#define NETCA_PKI_DEVICE_TYPE_HDSDKEY		35
/* 渔翁SJK Key*/
#define NETCA_PKI_DEVICE_TYPE_FMSJK		36
/* 天翼税通浪潮COS */
#define NETCA_PKI_DEVICE_TYPE_INSPURETAX		37
/* VAST虚拟设备 */
#define NETCA_PKI_DEVICE_TYPE_VAST			99
/* 得安的SJY05B加密机 */
#define NETCA_PKI_DEVICE_TYPE_SJY05B		100
/* 得安的SJY03B加密卡 */
#define NETCA_PKI_DEVICE_TYPE_SJY03B		101
/* 得安的SJJ0929加密机 */
#define NETCA_PKI_DEVICE_TYPE_SJJ0929	102
/* 普华SJJ1011加密机 */
#define NETCA_PKI_DEVICE_TYPE_SJJ1011	103
/* 渔翁加密卡 */
#define NETCA_PKI_DEVICE_TYPE_SJK0810		104
/* GDCA明华二版的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_GDCAEKPKXC_V2 401
/* GDCA明华三版的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_GDCAEKPKXC_V3 402
/* GDCA握奇的EKey */
#define NETCA_PKI_DEVICE_TYPE_GDCAWATCHKEY		403
/* SZCA飞天3003 */
#define NETCA_PKI_DEVICE_TYPE_SZCAEPASS3003		421

/* 设备类别 */
#define NETCA_DEVICE_CLASS_UNKNOWN		0
#define NETCA_DEVICE_CLASS_USB			1
#define NETCA_DEVICE_CLASS_PCI			2
#define NETCA_DEVICE_CLASS_NETWORK		3
#define NETCA_DEVICE_CLASS_COM			4
#define NETCA_DEVICE_CLASS_BUILDIN		5
#define NETCA_DEVICE_CLASS_PCSC			6
#define NETCA_DEVICE_CLASS_ICCARD		7


#define NETCA_PKI_DEVICE_FLAG_SILENT					1
#define NETCA_PKI_DEVICE_FLAG_CACHE_PIN_IN_PROCESS		(0<<1)
#define NETCA_PKI_DEVICE_FLAG_CACHE_PIN_IN_HANDLE		(1<<1)
#define NETCA_PKI_DEVICE_FLAG_NOT_CACHE_PIN				(2<<1)
#define NETCA_PKI_DEVICE_FLAG_CAN_INSTALL_CERT			0x100






#define NETCA_PKI_BASE64_NO_NL		1
#define NETCA_PKI_BASE64_STRICT		2

/* 最大可能的分组加密的分组长度 */
#define NETCA_PKI_CRYPT_BLOCK_MAXLEN	256

#define NETCA_PKI_PADDING_NONE		1
#define NETCA_PKI_PADDING_PKCS5		2


#define NETCA_PKI_CERT_ENCODE_DER				1
#define NETCA_PKI_CERT_ENCODE_BASE64			2
#define NETCA_PKI_CERT_ENCODE_BASE64_NO_NL		3

#define NETCA_PKI_CERT_ATTRIBUTE_PRIVKEY_ATTRIBUTE			1
#define NETCA_PKI_CERT_ATTRIBUTE_VERSION					2
#define NETCA_PKI_CERT_ATTRIBUTE_SIGNALGO					3
#define NETCA_PKI_CERT_ATTRIBUTE_PUBKEYALGO					4
#define NETCA_PKI_CERT_ATTRIBUTE_PUBKEYBITS					5
#define NETCA_PKI_CERT_ATTRIBUTE_KEYUSAGE					6
#define NETCA_PKI_CERT_ATTRIBUTE_HAS_PRIVKEY_ATTRIBUTE		7
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER						8
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_DISPLAY_NAME		9
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_C					10
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_O					11
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_OU					12
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_CN					13
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_EMAIL				14
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT					15
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_DISPLAY_NAME		16
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_C					17
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_O					18
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_OU					19
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_CN					20
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_EMAIL				21
#define NETCA_PKI_CERT_ATTRIBUTE_EX_FRIENDLY_NAME			22
#define NETCA_PKI_CERT_ATTRIBUTE_EX_NAME					23
#define NETCA_PKI_CERT_ATTRIBUTE_EX_ORGANIZATION			24
#define NETCA_PKI_CERT_ATTRIBUTE_EX_DEPARTMENT				25
#define NETCA_PKI_CERT_ATTRIBUTE_EX_EMAIL					26
#define NETCA_PKI_CERT_ATTRIBUTE_GET_KEYPAIR_HADNLE_NEED_PWD		27
#define NETCA_PKI_CERT_ATTRIBUTE_KEYPAIR_HADNLE				28
#define NETCA_PKI_CERT_ATTRIBUTE_PREVCERT_THUMBPRINT		29
#define NETCA_PKI_CERT_ATTRIBUTE_VALIDITY_START				30
#define NETCA_PKI_CERT_ATTRIBUTE_VALIDITY_END				31
/* 十进制证书序列号 */
#define NETCA_PKI_CERT_ATTRIBUTE_SN_DEC						32
/* 十六进制证书序列号 */
#define NETCA_PKI_CERT_ATTRIBUTE_SN_HEX						33
#define NETCA_PKI_CERT_ATTRIBUTE_IN_VALIDITY				34
#define NETCA_PKI_CERT_ATTRIBUTE_PRIVATE_ISCSP				35
#define NETCA_PKI_CERT_ATTRIBUTE_UPN						36
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_ST					37
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_L					38
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_ST					39
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_L					40
#define NETCA_PKI_CERT_ATTRIBUTE_EX_DEVICE_TYPE				41
#define NETCA_PKI_CERT_ATTRIBUTE_EX_DEVICE_SN				42
#define NETCA_PKI_CERT_ATTRIBUTE_PUBKEY_ECC_CURVE			43
#define NETCA_PKI_CERT_ATTRIBUTE_THUMBPRINT					44
#define NETCA_PKI_CERT_ATTRIBUTE_HASH_ISSUER				45
#define NETCA_PKI_CERT_ATTRIBUTE_HASH_SUBJECT				46
#define NETCA_PKI_CERT_ATTRIBUTE_HASH_PUBKEY				47
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_LDAP_NAME			48
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_XMLSIG_NAME			49
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_LDAP_NAME			50
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_XMLSIG_NAME		51
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_HEX_ENCODE			52
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_HEX_ENCODE			53






#define NETCA_PKI_SEARCH_KEYPAIR_FLAG_DEVICE				0x10000000
#define NETCA_PKI_SEARCH_KEYPAIR_FLAG_LOCAL_MACHINE			0x20000000
#define NETCA_PKI_SEARCH_KEYPAIR_FLAG_CURRENT_USER			0x40000000

#define NETCA_PKI_CERT_PURPOSE_ENCRYPT			1
#define NETCA_PKI_CERT_PURPOSE_SIGN				2
#define NETCA_PKI_CERT_PURPOSE_KEYAGREEMENT		4
#define NETCA_PKI_CERT_PURPOSE_VERIFY_OLD_DATA	0x10000002
#define NETCA_PKI_CERT_PURPOSE_DECRYPT_WITH_OLD_CERT	0x10000001


#define NETCA_PKI_USAGE_ENCRYPT			1
#define NETCA_PKI_USAGE_DECRYPT			2
#define NETCA_PKI_USAGE_HASH			3
#define NETCA_PKI_USAGE_MAC				4
#define NETCA_PKI_USAGE_SIGN			5
#define NETCA_PKI_USAGE_VERIFY			6
#define NETCA_PKI_USAGE_GENKEYPAIR		7
#define NETCA_PKI_USAGE_KEYAGREEMENT	8
#define NETCA_PKI_USAGE_IMPORTKEY_FOR_ENCRYPT	9
#define NETCA_PKI_USAGE_IMPORTKEY_FOR_DECRYPT	10
#define NETCA_PKI_USAGE_IMPORTKEYPAIR	11


#define NETCA_PKI_CERT_VERSION_V1			0
#define NETCA_PKI_CERT_VERSION_V2			1
#define NETCA_PKI_CERT_VERSION_V3			2


#define NETCA_PKI_CERT_TYPE_LOCAL_MACHINE		0x8000

#define NETCA_PKI_CERT_STORE_TYPE_CURRENT_USER		0
#define NETCA_PKI_CERT_STORE_TYPE_LOCAL_MACHINE		1
#define NETCA_PKI_CERT_STORE_TYPE_MEMORY			2

#define NETCA_PKI_CERT_STORE_NAME_MY		"my"
#define NETCA_PKI_CERT_STORE_NAME_OTHERS	"others"
#define NETCA_PKI_CERT_STORE_NAME_CA		"ca"
#define NETCA_PKI_CERT_STORE_NAME_ROOT		"root"


#define NETCA_PKI_CERTVERIFY_OPTION_USEV1CERT			0x1
#define NETCA_PKI_CERTVERIFY_OPTION_USEALLCACERT		0x2
#define NETCA_PKI_CERTVERIFY_OPTION_IGNOREALLEXT		0x4
#define NETCA_PKI_CERTVERIFY_OPTION_VERIFYEEREVOKE		0x8
#define NETCA_PKI_CERTVERIFY_OPTION_VERIFYCAREVOKE		0x10
#define NETCA_PKI_CERTVERIFY_OPTION_ONLINE_GETCACERT	0x20
#define NETCA_PKI_CERTVERIFY_OPTION_ONLINE_GETREVOKEINFO	0x40



#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_DESCBC		1
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_RC2CBC		2
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_TDESCBC		3
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_AES128CBC		4
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_AES192CBC		5
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_AES256CBC		6
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SSF33CBC		7
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SM1CBC		8
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SMS4CBC		9
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SM4CBC		9

#define NETCA_PKI_ENVELOPEDDATA_FLAG_USEKEYID			1


#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_REVOKE				1
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_ONLINE					2
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_CACERT_REVOKE		4
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_OCSP				0x10
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_CRL				0x20


#define NETCA_PKI_CERTIFICATE_STATUS_UNREVOKED						1
#define NETCA_PKI_CERTIFICATE_STATUS_UNDETERMINED					-1
#define NETCA_PKI_CERTIFICATE_STATUS_REVOKED						0
#define NETCA_PKI_CERTIFICATE_STATUS_CA_REVOKED                     -2

#define NETCA_PKI_CRL_REASON_UNSPECIFIED				0
#define NETCA_PKI_CRL_REASON_KEYCOMPROMISE				1
#define NETCA_PKI_CRL_REASON_CACOMPROMISE				2
#define NETCA_PKI_CRL_REASON_AFFILIATION_CHANGED		3
#define NETCA_PKI_CRL_REASON_SUPERSEDED					4
#define NETCA_PKI_CRL_REASON_CESSATION_OF_OPERATION		5
#define NETCA_PKI_CRL_REASON_CERTIFATE_HOLD				6
#define NETCA_PKI_CRL_REASON_REMOVE_FROM_CRL			8
#define NETCA_PKI_CRL_REASON_PRIVILEGE_WITHDRAWN		9
#define NETCA_PKI_CRL_REASON_AACOMPROMISE				10

#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNER_COUNT					1
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_DETACHED						2
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGN_ALGO					3
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SIGNINGTIME				4
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_CONTENT_INFO				5
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_KEYID					6
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_INCLUDE_CERT_OPTION			7
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_KEEP_TBS						8
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SIGNINGCERT				9
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNINGCERTV2_HASH_ALGO		10
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNINGTIME					11
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TSATIME						12
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CONTENT_OID					13
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_VALIDITY				14
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_TSATIME					15
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TIMESTAMP_SERIAL_NUMBER		16
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TIMESTAMP_POLICY				17
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TIMESTAMP_HASH_ALGO			18
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COUNTERSIGNATURE_COUNT		19
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNEDATTRS_COUNT			20
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_UNSIGNEDATTRS_COUNT			21
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNATURE_VALUE				22
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SM2_Q7					23
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SM2SIGN_OID				24
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_PKCS7					25

#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_NONE				1
#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_SELF				2
#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_CERTPATH			3
#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_CERTPATHWITHROOT	4



#define NETCA_PKI_KEYUSAGE_DIGITALSIGNATURE				(1<<0)
#define NETCA_PKI_KEYUSAGE_NONREPUDIATION				(1<<1)
#define NETCA_PKI_KEYUSAGE_CONTENTCOMMITMENT			(1<<1)
#define NETCA_PKI_KEYUSAGE_KEYENCIPHERMENT				(1<<2)
#define NETCA_PKI_KEYUSAGE_DATAENCIPHERMENT				(1<<3)
#define NETCA_PKI_KEYUSAGE_KEYAGREEMENT					(1<<4)
#define NETCA_PKI_KEYUSAGE_KEYCERTSIGN					(1<<5)
#define NETCA_PKI_KEYUSAGE_CRLSIGN						(1<<6)
#define NETCA_PKI_KEYUSAGE_ENCIPHERONLY					(1<<7)
#define NETCA_PKI_KEYUSAGE_DECIPHERONLY					(1<<8)


#define NETCA_PKI_DATA_ID_COMMON_BASE		0x100

#define NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_NAME				0
#define NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_FRIENDLY_NAME		1
#define	NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_ORGANIZATION		2
#define	NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_DEPARTMENT			3
#define	NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_EMAIL				4
#define NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_PHONE			5

/* 联系人属性类型 */
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_ENCCERT		0
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_SIGNCERT		1
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_FRIENDLYNAME		2
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_ORGANIZATION		3
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_DEPARTMENT		4
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_EMAIL		5
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_PHONE		6
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_COMMENT		7

#define	NETCA_PKI_PROMTMSG_FLAG_NO_ARGUMENT			0
#define	NETCA_PKI_PROMTMSG_FLAG_ONE_ARGUMENT		1


#define NETCA_PKI_TIMESTAMP_RESP_STATUS_BADRESP					-1
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_BADTSACERT				-2
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_GRANTED   				0
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_GRANTEDWITHMODS			1
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_REJECTION				2
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_WAITING					3
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_REVOCATIONWARNING		4
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_REVOCATIONNOTIFICATION	5


#define NETCA_PKI_CERTREQ_VERSION					1
#define NETCA_PKI_CERTREQ_SIGN_ALGO					2
#define NETCA_PKI_CERTREQ_SUBJECT					3
#define NETCA_PKI_CERTREQ_SUBJECT_REVERSE			4
#define NETCA_PKI_CERTREQ_SUBJECT_C					5
#define NETCA_PKI_CERTREQ_SUBJECT_ST				6
#define NETCA_PKI_CERTREQ_SUBJECT_L					7
#define NETCA_PKI_CERTREQ_SUBJECT_O					8
#define NETCA_PKI_CERTREQ_SUBJECT_OU				9
#define NETCA_PKI_CERTREQ_SUBJECT_CN				10
#define NETCA_PKI_CERTREQ_SUBJECT_EMAIL				11
#define NETCA_PKI_CERTREQ_SUBJECT_MULTI_OU			12
#define NETCA_PKI_CERTREQ_SUBJECT_MULTI_CN			13
#define NETCA_PKI_CERTREQ_SUBJECT_ENCODE_PARAM		14

/* 旧的个性化信息的ID */
#define NETCA_PKI_DATAID_OLD_CUSTOMINFO				999

#define NETCA_PKI_EXTENSION_TYPE_OCTETSTRING			1
#define NETCA_PKI_EXTENSION_TYPE_OID					2
#define NETCA_PKI_EXTENSION_TYPE_UTF8STRING				3
#define NETCA_PKI_EXTENSION_TYPE_NUMERICSTRING			4
#define NETCA_PKI_EXTENSION_TYPE_PRINTABLESTRING		5
#define NETCA_PKI_EXTENSION_TYPE_TELETEXSTRING			6
#define NETCA_PKI_EXTENSION_TYPE_VIDEOTEXSTRING			7
#define NETCA_PKI_EXTENSION_TYPE_IA5STRING				8
#define NETCA_PKI_EXTENSION_TYPE_GRAPHICSTRING			9
#define NETCA_PKI_EXTENSION_TYPE_VISIBLESTRING			10
#define NETCA_PKI_EXTENSION_TYPE_GENERALSTRING			11
#define NETCA_PKI_EXTENSION_TYPE_UNIVERSALSTRING		12
#define NETCA_PKI_EXTENSION_TYPE_BMPSTRING				13


#define NETCA_PKI_ENCKEYPAIR_TYPE_NONE			0
#define NETCA_PKI_ENCKEYPAIR_TYPE_3				1
#define NETCA_PKI_ENCKEYPAIR_TYPE_06			2
#define NETCA_PKI_ENCKEYPAIR_TYPE_PUHUA			3
#define NETCA_PKI_ENCKEYPAIR_TYPE_GDKM			4


#define NETCA_PKI_CONFIGNURE_STORE_FLAG_RESTORE		2
#define NETCA_PKI_CONFIGNURE_STORE_FLAG_ADDTEMP		1
#define NETCA_PKI_CONFIGNURE_STORE_FLAG_REPLACE		0


#ifdef __cplusplus
	}	
#endif
#endif
