#ifndef _NETCA_PKI_CONST_INLCUDE_H_
#define _NETCA_PKI_CONST_INLCUDE_H_

#ifdef __cplusplus
extern "C"
	{
#endif

#ifndef NETCADLLAPI

	#ifdef _WIN32
		#define NETCADLLAPI __stdcall
	#else
		#define NETCADLLAPI
	#endif

#endif

/*	错误码 */
/* 成功 */
#define NETCA_PKI_SUCCESS			1
/* 失败 */
#define NETCA_PKI_FAIL				0
/* 无效的参数 */
#define NETCA_PKI_INVALIDARG		-1
/* 无效的句柄 */
#define NETCA_PKI_INVALIDHANDLE		-2
/* 内存分配失败 */
#define NETCA_PKI_OUTOFMEMORY		-3
/* 输出缓冲区太小 */
#define NETCA_PKI_MOREDATA			-4
/* 密码错误 */
#define NETCA_PKI_PWD_ERROR			-5
/* 已经存在 */
#define NETCA_PKI_EXISIT			-6
/* 不存在 */
#define NETCA_PKI_NOTEXISIT			-7
/* 拒绝访问 */
#define NETCA_PKI_ACCESSDENIED		-8
/* 不支持 */
#define NETCA_PKI_UNSUPPORTED		-9
/* 未实现 */
#define NETCA_PKI_NOTIMPLEMENT		-10
/* 超时 */
#define NETCA_PKI_TIMEOUT			-11
/* 构造证书链失败 */
#define NETCA_PKI_BULID_CERTPATH_FAIL		-12
/* 验证证书链失败 */
#define NETCA_PKI_VERIFY_CERTPATH_FAIL		-13
/* 不在有效期内 */
#define NETCA_PKI_NOT_IN_VALIDITY			-14
/* CRL或OCSP不在有效期内 */
#define NETCA_PKI_REVOKEINFO_NOT_IN_VALIDITY	-15
/* 不符合安全环境的要求 */
#define NETCA_PKI_VIOLATE			-16
/* 没有装载UI的共享库 */
#define NETCA_PKI_NOUI			-17
/* 用户取消了操作 */
#define NETCA_PKI_USER_CANCEL		-18
/* 密码长度错误 */
#define NETCA_PKI_PWD_LENGTH_ERROR		-19
/* 密码格式错误 */
#define NETCA_PKI_PWD_FORMAT_ERROR		-20
/* 数据长度过大 */
#define NETCA_PKI_DATATOOLONG				-21
/* 密码没有被锁死 */
#define NETCA_PKI_PWD_NOTLOCK				-22
/* 加密证书没有匹配的加密密钥对 */
#define NETCA_PKI_ENC_KEYPAIR_NOTFOUND		-23
/* 签名证书没有匹配的密钥对 */
#define NETCA_PKI_SIGN_KEYPAIR_NOTFOUND		-24
/* 没有匹配的设备 */
#define NETCA_PKI_NOSUCHDEVICE				-25
/* 没有匹配的密钥对 */
#define NETCA_PKI_NOSUCHKEYPAIR				-26
/* 证书匹配表达式错误 */
#define NETCA_PKI_BADCERTMATCHEXPR			-27
/* 没有根证书 */
#define NETCA_PKI_NO_ROOTCERT				-28
/* 没有合适的作废信息 */
#define NETCA_PKI_NO_REVOKE_INFO			-29
/* 没有合适的CA作废信息 */
#define NETCA_PKI_NO_CA_REVOKE_INFO			-30
/* 验证MAC失败 */
#define NETCA_PKI_VERIFY_MAC_FAIL			-31
/* 验证SignedData时，至少一个SignerInfo成功，其他的失败 */
#define NETCA_PKI_VERIFY_SIGNEDDATA_PARTLY_FAIL			-32
/* 不支持HTTP */
#define NETCA_PKI_HTTP_UNSUPPORTED			-33
/* 不支持LDAP */
#define NETCA_PKI_LDAP_UNSUPPORTED			-34
/* 不是S/MIME */
#define NETCA_PKI_NOT_SMIME					-35
/* 验证SignedData的证书失败 */
#define NETCA_PKI_VERIFY_SIGNEDDATA_CERT_FAIL	-36
/* EnvelopedData格式错误 */
#define NETCA_PKI_ENVELOPEDDATA_BAD_DATA	-37
/* EnvelopedData解密对称密钥失败 */
#define NETCA_PKI_ENVELOPEDDATA_DECRYPT_KEY_FAIL	-38
/* EnvelopedData解密数据失败 */
#define NETCA_PKI_ENVELOPEDDATA_DECRYPT_DATA_FAIL	-39
/* EnvelopedData没有匹配的证书用于解密对称密钥 */
#define NETCA_PKI_ENVELOPEDDATA_NO_MATCH_CERT		-40
/* SignedData格式错误 */
#define NETCA_PKI_SIGNEDDATA_BAD_DATA				-41
/* 验证SignedData的Content-Type失败 */
#define NETCA_PKI_SIGNEDDATA_VERIFY_CONTENT_TYPE_FAIL	-42
/* 验证SignedData的Hash失败 */
#define NETCA_PKI_SIGNEDDATA_VERIFY_HASH_FAIL		-43
/* 验证SignedData的签名失败 */
#define NETCA_PKI_SIGNEDDATA_VERIFY_SIGNATURE_FAIL	-44
/* 没有签名证书用于验证SignedData的签名 */
#define NETCA_PKI_SIGNEDDATA_NO_MATCH_CERT			-45
/* 验证证书路径的签名失败 */
#define NETCA_PKI_VERIFY_CERTPATH_SIGNATURE_FAIL	-46
/* 验证证书路径的基本限制失败 */
#define NETCA_PKI_VERIFY_CERTPATH_BASIC_CONSTRAINTS_FAIL	-47
/* 验证证书路径的策略相关扩展失败 */
#define NETCA_PKI_VERIFY_CERTPATH_POLICY_FAIL	-48
/* 验证证书路径的名字和名字约束失败 */
#define NETCA_PKI_VERIFY_CERTPATH_NAME_FAIL	-49
/* 验证证书路径时存在未知关键扩展 */
#define NETCA_PKI_VERIFY_CERTPATH_UNKNOWN_CRITICAL_EXTENSION_EXIST	-50
/* 验证证书路径的KeyUsage失败 */
#define NETCA_PKI_VERIFY_CERTPATH_KEY_USAGE_FAIL	-51
/* 验证时间戳的MessageImprint失败 */
#define NETCA_PKI_VERIFY_TIMESTAMP_MESSAGE_IMPRINT_FAIL	-52
/* 错误的填充数据 */
#define NETCA_PKI_BAD_PADDING						-53
/* 签名算法和密钥对不匹配 */
#define NETCA_PKI_SIGNALGO_KEYPAIR_MISMATCH			-54
/* 签名算法和公钥不匹配 */
#define NETCA_PKI_SIGNALGO_PUBLICKEY_MISMATCH		-55
/* 加密算法和公钥不匹配 */
#define NETCA_PKI_ENCALGO_PUBLICKEY_MISMATCH		-56
/* 加密算法和密钥对不匹配 */
#define NETCA_PKI_ENCALGO_KEYPAIR_MISMATCH			-57
/* 密钥协商算法和密钥对不匹配 */
#define NETCA_PKI_KEYAGREEMENTALGO_KEYPAIR_MISMATCH	-58
/*  错误的CRL的编码 */
#define NETCA_PKI_BAD_CRL_ENCODE					-59
/*  错误的OCSP响应的编码 */
#define NETCA_PKI_BAD_OCSPRESP_ENCODE				-60
/* EnvelopedData错误的加密算法 */
#define NETCA_PKI_ENVELOPEDDATA_BAD_ENCALGO			-61
/* EnvelopedData错误的加密证书 */
#define NETCA_PKI_ENVELOPEDDATA_BAD_CERT			-62
/* EnvelopedData加密出错 */
#define NETCA_PKI_ENVELOPEDDATA_ENCRYPT_FAIL		-63
/* 证书没有Subjet Key Id扩展 */
#define NETCA_PKI_NO_SUBJCT_KEY_ID					-64
/* 不是签名证书 */
#define NETCA_PKI_NOT_SIGNCERT						-65
/* 不是加密证书 */
#define NETCA_PKI_NOT_ENCCERT						-66
/*  错误的属性的编码 */
#define NETCA_PKI_BAD_ATTRIBUTE						-67
/* SignedData签名进行Hash运算失败 */
#define NETCA_PKI_SIGNEDDATA_HASH_FAIL				-68
/* SignedData签名进行签名运算失败 */
#define NETCA_PKI_SIGNEDDATA_SIGN_FAIL				-69
/* SignedData签名进行编码失败 */
#define NETCA_PKI_SIGNEDDATA_ENCODE_FAIL			-70
/* SignedData签名创建SID失败 */
#define NETCA_PKI_SIGNEDDATA_CREATE_SID_FAIL		-71
/* SignedData签名追加时间戳失败 */
#define NETCA_PKI_SIGNEDDATA_ADD_SIGNATURE_TIMESTAMP_FAIL		-72
/* 获取时间戳失败 */
#define NETCA_PKI_GET_TIMESTAMP_FAIL				-73
/* 连接服务器失败 */
#define NETCA_PKI_CONNET_FAIL						-74
/* HTTP失败 */
#define NETCA_PKI_HTTP_FAIL							-75
/* LDAP失败 */
#define NETCA_PKI_LDAP_FAIL							-76
/* 获取配置失败 */
#define NETCA_PKI_GET_CONFIG_FAIL				-77
/* 获取公钥失败 */
#define NETCA_PKI_GET_PUBLICKEY_FAIL			-78
/* 转化为国密DER编码的SM2密文失败 */
#define NETCA_PKI_TODERSM2CIPHER_FAIL		-79
/* 错误的国密DER编码的SM2密文 */
#define NETCA_PKI_BAD_DERSM2CIPHER			-80
/* 获取密钥对失败 */
#define NETCA_PKI_GET_KEYPAIR_FAIL			-81
/* 不可接受的数字信封对称加密算法 */
#define NETCA_PKI_ENVELOPEDDATA_UNACCEPTABLE_ENCALGO	-82
/* 数字信封ContentInfo不匹配 */
#define NETCA_PKI_ENVELOPEDDATA_OUTER_CONTENTINFO_MISMATCH -83
/* SignedData的原文不匹配 */
#define NETCA_PKI_SIGNEDDATA_TBS_MISMATCH	-84
/* SignedData的签名证书不匹配 */
#define NETCA_PKI_SIGNEDDATA_SIGNEDCERT_MISMATCH	-85
/* 不可接受的SignedData签名算法 */
#define NETCA_PKI_SIGNEDDATA_UNACCEPTABLE_SIGNALGO	-86
/* SignedData的ContentInfo不匹配 */
#define NETCA_PKI_SIGNEDDATA_OUTER_CONTENTINFO_MISMATCH -87
/* 不可接受的SigningCert属性 */
#define NETCA_PKI_SIGNEDDATA_UNACCEPTABLE_SIGNINGCERT_ATTRIBUTE	-88
/* 没有时间戳的配置 */
#define NETCA_PKI_NO_TIMESTAMP_CONFIG	-89
/* 不可接受的时间戳Hash算法 */
#define NETCA_PKI_TIMESTAMP_UNACCEPTABLE_HASHALGO	-90
/* 不可接受的时间戳策略 */
#define NETCA_PKI_TIMESTAMP_UNACCEPTABLE_POLICY		-91
/* 没有输入密码 */
#define NETCA_PKI_NO_PWD		-92
/* 错误的设备ID */
#define NETCA_PKI_BAD_DEVICE_ID	-93
/* 不可接受的签名时间戳 */
#define NETCA_PKI_SIGNEDDATA_UNACCEPTABLE_SIGNATURE_TIMESTAMP	-94
/* 需要输入更多的数据，否则无法判断  */
#define NETCA_PKI_NEED_MORE_DATA			-95
/* 保存设备DLL文件失败  */
#define NETCA_PKI_SAVE_DEVICE_DLL_FILE_FAIL			-96
/* 验证RSA PSS参数失败  */
#define NETCA_PKI_VERIFY_PSS_PARAM_FAIL			-97
/* 验证TLS服务器证书失败 */
#define NETCA_PKI_BAD_TLS_CERT						-98
/* 既没有ATS_HASH_INDEX属性也没有ATS_HASH_INDEX_V3属性 */
#define NETCA_PKI_NO_ATS_HASH_INDEX				-99
/* JWS的头中存在重复的项 */
#define NETCA_PKI_JWS_DUP_HEADER				-100
/* JWS的紧凑序列化不能有不保护的头 */
#define NETCA_PKI_JWS_COMPACT_CANNOT_HAVE_UNPROTECTED_HEADER				-101
/* 不支持的JWS签名算法或MAC算法 */
#define NETCA_PKI_JWS_UNSUPPORTED_SIGNALGO				-102
/* 证书和JWS签名算法不匹配 */
#define NETCA_PKI_JWS_CERT_MISMATCH_SIGNALGO			-103
/* JWS进行签名运算失败 */
#define NETCA_PKI_JWS_SIGN_FAIL							-104
/* JWS进行MAC运算失败 */
#define NETCA_PKI_JWS_MAC_FAIL							-105
/* JWS的MAC长度太短 */
#define NETCA_PKI_JWS_BAD_MAC_LENGTH					-106
/* JWS签名不是签名，而是MAC */
#define NETCA_PKI_JWS_NOT_SIGNATURE						-107
/* JWS签名不是MAC，而是签名 */
#define NETCA_PKI_JWS_NOT_MAC							-108
/* JWS签名验证MAC失败 */
#define NETCA_PKI_JWS_VERIFY_MAC_FAIL					-109
/* JWS签名的证书相关头出错 */
#define NETCA_PKI_JWS_BAD_CERT							-110
/* JWS签名的没有匹配的证书 */
#define NETCA_PKI_JWS_NO_SIGNCERT						-111
/* JWS验证签名失败 */
#define NETCA_PKI_JWS_VERIFY_SIGNATURE_FAIL				-112
/* JWE的头中存在重复的项 */
#define NETCA_PKI_JWE_DUP_HEADER						-113
/* JWE的紧凑序列化不能有不保护的头 */
#define NETCA_PKI_JWE_COMPACT_CANNOT_HAVE_UNPROTECTED_HEADER				-114
/* JWE的紧凑序列化不能有多于一个接收者 */
#define NETCA_PKI_JWE_COMPACT_TOO_MUCH_RECIPIENT		-115
/* ECDH-ES算法不能有多于一个接收者 */
#define NETCA_PKI_ECDH_ES_TOO_MUCH_RECIPIENT			-116
/* 证书和JWE加密算法不匹配 */
#define NETCA_PKI_JWE_CERT_MISMATCH_ENCALGO				-117
/* JWE的两个加密算法不匹配 */
#define NETCA_PKI_JWE_MISMATCH_ENCALGO					-118
/* JWE进行加密运算失败 */
#define NETCA_PKI_JWE_ENCRYPT_FAIL						-119
/* JWE的紧凑序列化不能有AAD */
#define NETCA_PKI_JWE_COMPACT_CANNOT_HAVE_AAD			-120
/* 证书库中没有解密证书 */
#define NETCA_PKI_STORE_NO_DECRYPT_CERT					-121
/* JWE解密CEK失败 */
#define NETCA_PKI_JWE_DECRYPT_CEK_FAIL					-122
/* JWE解密数据失败 */
#define NETCA_PKI_JWE_DECRYPT_DATA_FAIL					-123
/* JWE解密没有匹配的解密证书或者没有指定解密的密钥 */
#define NETCA_PKI_JWE_NO_MATCH_CERT						-124
/* JWE dir算法不能有多于一个接收者 */
#define NETCA_PKI_JWE_DIR_TOO_MUCH_RECIPIENT			-125
/* 密钥长度和JWE加密算法不匹配 */
#define NETCA_PKI_JWE_KEYLEN_MISMATCH_ENCALGO			-126
/* JWT不是签名类型不能进行签名 */
#define NETCA_PKI_JWT_CANNOT_SIGN						-127
/* JWT不是签名类型不能进行MAC */
#define NETCA_PKI_JWT_CANNOT_MAC						-128
/* JWT不是加密类型不能进行加密 */
#define NETCA_PKI_JWT_CANNOT_ENCRYPT					-129
/* JWT不是签名类型不能进行验证签名 */
#define NETCA_PKI_JWT_CANNOT_VERIFY_SIGN				-130
/* JWT不是签名类型不能进行验证MAC */
#define NETCA_PKI_JWT_CANNOT_VERIFY_MAC					-131
/* JWT不是加密类型不能进行解密 */
#define NETCA_PKI_JWT_CANNOT_DECRYPT					-132
/* JWT解密后得到的明文不是Claims */
#define NETCA_PKI_JWT_CLEARTEXT_NOT_CLAIMS				-133
/* 嵌套JWT解密后得到的明文不是JWT */
#define NETCA_PKI_JWT_CLEARTEXT_NOT_JWT					-134
/* 验证证书路径的AKID和SKID失败 */
#define NETCA_PKI_VERIFY_CERTPATH_AKID_SKID_MISMATCH	-135
/* b64头冲突 */
#define NETCA_PKI_B64_HEADER_CONFLICT					-136
/* 禁止使用初始的用户密码 */
#define NETCA_PKI_FORBID_INIT_USER_PWD					-137
/* 证书在不信任的证书库中 */
#define NETCA_PKI_CERT_IN_BLACKLIST						-138
/* CA证书在不信任的证书库中 */
#define NETCA_PKI_CACERT_IN_BLACKLIST					-139
/* 模板错误 */
#define NETCA_PKI_TEMPLATE_FAIL							-140
/* 模板数据错误 */
#define NETCA_PKI_TEMPLATE_DATA_FAIL					-141
/* 不能产生SM9的用户密钥对 */
#define NETCA_PKI_CANT_GENERATE_SM9_USER_KEYPAIR		-142
/* 本机时间和时间戳服务器时间差太远 */
#define NETCA_PKI_TSA_CLOCKSKEW							-143
/* SignedAndEnvelopedData格式错误 */
#define NETCA_PKI_BAD_SIGNED_AND_ENVELOPED_DATA			-144
/* SM2的SignedAndEnvelopedData格式错误 */
#define NETCA_PKI_BAD_SM2_SIGNED_AND_ENVELOPED_DATA		-145
/* SignedAndEnvelopedData有属性 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_HAS_ATTRIBUTE	-146
/* SignedAndEnvelopedData未知的加密算法 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_UNKNOWN_ENC_ALGO -147
/* SignedAndEnvelopedData解密密钥失败 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_DECRYPT_KEY_FAIL -148
/* SignedAndEnvelopedData没有匹配的解密证书 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_NO_DECRYPT_CERT -149
/* SignedAndEnvelopedData解密数据失败 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_DECRYPT_DATA_FAIL -150
/* SignedAndEnvelopedData解密签名失败 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_DECRYPT_SIGNATURE_FAIL -151
/* SignedAndEnvelopedData没有匹配的验证证书 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_NO_VERIFY_CERT -152
/* SignedAndEnvelopedData验证签名失败 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_VERIFY_FAIL -153
/* SignedAndEnvelopedData签名证书不在有效期内 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_SIGN_CERT_NOT_IN_VALIDITY -154
/* 随机数测试失败 */
#define NETCA_PKI_RANDOM_TEST_FAIL -155
/* 是CA证书 */
#define NETCA_PKI_ISCACERT -156
/* 不是颁发者证书 */
#define NETCA_PKI_NOT_ISSUER_CERT -157
/* 验证签名失败 */
#define NETCA_PKI_VERIFY_SIGNATURE_FAIL -158
/* 设置不带原文的SignedData的Hash值得长度不匹配 */
#define NETCA_PKI_DETACHED_SIGNEDDATA_HASH_LENGTH_MISMATCH -159
/* 不是EncryptedData编码 */
#define NETCA_PKI_BAD_ENCRYPTED_DATA -160
/* 证书请求签名失败 */
#define NETCA_PKI_CERTREQ_SIGN_FAIL                     -161
/* 电子印章不在有效期内 */
#define NETCA_PKI_STAMP_NOT_IN_VALIDITY                  -162
/* 签章人证书不在电子印章中 */
#define NETCA_PKI_SIGNCERT_NOT_IN_STAMP                  -163
/* Hash长度不对 */
#define NETCA_PKI_HASH_LENGTH_MISMATCH                   -164
/* 验证电子印章失败 */
#define NETCA_PKI_VERIFY_STAMP_FAIL                      -165
/* 电子签章时间格式错误 */
#define NETCA_PKI_BAD_SEAL_TIMEINFO_FORMAT               -166
/* 电子印章签名失败 */
#define NETCA_PKI_STAMP_SIGN_FAIL						 -167
/* 电子签章签名失败 */
#define NETCA_PKI_SEAL_SIGN_FAIL						 -168
/* GB/T 38540的电子印章和电子签章的版本号必须为4 */
#define NETCA_PKI_GBT_38540_BAD_VERSION					 -169
/* 电子签章和电子印章的格式不匹配 */
#define NETCA_PKI_SEAL_STAMP_FORMAT_MISMATCH			 -170
/* SignedAndEnvelopedData签名失败 */
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_SIGN_FAIL    -171
/* 不是GM/T 0031的电子印章 */
#define NETCA_PKI_NOT_GMT_0031_SEAL						 -172

/* 应用密码错误 */
#define NETCA_PKI_APP_PWD_ERROR				0x10000

/*  打开设备库失败 */
#define NETCA_PKI_ERROR_OPEN_DEVICE_STORE_FAIL			0x20000
/*  在设备库进行过滤失败 */
#define NETCA_PKI_ERROR_FILTER_DEVICE_STORE_FAIL		0x20001
/*  错误的设备类型 */
#define NETCA_PKI_ERROR_BAD_DEVICE_TYPE					0x20002
/*  索引值超出了范围 */
#define NETCA_PKI_ERROR_OUT_OF_RANGE					0x20003
/*  验证设备DLL签名失败 */
#define NETCA_PKI_ERROR_VERIFY_DEVICE_DLL_FAIL			0x20004
/*  装载设备DLL签名失败 */
#define NETCA_PKI_ERROR_LOAD_DEVICE_DLL_FAIL			0x20005
/*  DeviceGetAllDevices失败 */
#define NETCA_PKI_ERROR_GET_ALL_DEVICE_FAIL				0x20006
/*  获取第一个设备失败 */
#define NETCA_PKI_ERROR_GET_FIRST_DEVICE_FAIL			0x20007
/*  加锁失败 */
#define NETCA_PKI_ERROR_LOCK_FAIL						0x20008
/*  解锁失败 */
#define NETCA_PKI_ERROR_UNLOCK_FAIL						0x20009
/*  获取密钥对数目失败 */
#define NETCA_PKI_ERROR_GET_KEYPAIR_COUNT_FAIL			0x2000A
/*  获取密钥对失败 */
#define NETCA_PKI_ERROR_GET_KEYPAIR_FAIL				0x2000B
/*  错误的SubjectPublicKeyInfo的编码 */
#define NETCA_PKI_ERROR_BAD_SUBJECT_PUBKEY_INFO			0x2000C
/*  错误的公钥证书的编码 */
#define NETCA_PKI_ERROR_BAD_CERT_ENCODE					0x2000D
/*  错误的公钥证书使用目的 */
#define NETCA_PKI_ERROR_BAD_CERT_PURPOSE				0x2000E
/*  部分的公钥 */
#define NETCA_PKI_ERROR_PART_CERT_PUBLICKEY				0x2000F
/*  错误的PFX的编码 */
#define NETCA_PKI_ERROR_BAD_PFX_ENCODE					0x20010
/*  错误的PFX的密码 */
#define NETCA_PKI_ERROR_BAD_PFX_PWD						0x20011
/*  解密PFX出错 */
#define NETCA_PKI_ERROR_DECRYPT_PFX_FAIL				0x20012
/*  错误的P10的编码 */
#define NETCA_PKI_ERROR_BAD_P10_ENCODE					0x20013
/*  没有时间戳 */
#define NETCA_PKI_ERROR_NO_TIMESTAMP					0x20014
/*  使用了内置的软件设备 */
#define NETCA_PKI_ERROR_USE_BULIDIN_SOFTWARE_DEVICE		0x20015
/* 时间戳的Hash值不匹配 */
#define NETCA_PKI_ERROR_TIMESTAMP_HASH_MISMATCH			0x20016
/* 不是字符串类型的扩展 */
#define NETCA_PKI_ERROR_NOT_STRING_TYPE_EXT		0x20017
/* 字符串类型的扩展编码错误 */
#define NETCA_PKI_ERROR_BAD_STRING_EXT_ENCODE		0x20018
/* LDAP条目超出限制，但返回了数据 */
#define NETCA_PKI_ERROR_LDAP_SIZELIMIT_EXCEEDED			0x20019
/* LDAP超时，但返回了数据 */
#define NETCA_PKI_ERROR_LDAP_TIMELIMIT_EXCEEDED			0x2001A
/* JWS格式错误 */
#define NETCA_PKI_ERROR_BAD_JWS_DATA					0x2001B
/* JWE格式错误 */
#define NETCA_PKI_ERROR_BAD_JWE_DATA					0x2001C
/* JWT格式错误 */
#define NETCA_PKI_ERROR_BAD_JWT_DATA					0x2001D
/* 使用初始的用户密码来验证 */
#define NETCA_PKI_INIT_USER_PWD							0x2001E
/* 是Q7格式的EncryptedData编码 */
#define NETCA_PKI_Q7_ENCRYPTED_DATA                     0x2001F
/* 不是电子印章 */
#define NETCA_PKI_ERROR_NOT_ES_STAMP                    0x20020
/* 电子签章中的电子印章格式有问题 */
#define NETCA_PKI_ERROR_BAD_STAMP_IN_SEAL               0x20021
/* 电子签章中的签章时间是ASN.1的UTCTIME */
#define NETCA_PKI_SEAL_TIME_IS_ASN1_UTCTIME             0x20022

/* Hash算法 */
/* MD5算法 */
#define NETCA_PKI_ALGORITHM_MD5		0x1000
/* SHA-1算法 */
#define NETCA_PKI_ALGORITHM_SHA1	0x2000
/* SHA-224算法 */
#define NETCA_PKI_ALGORITHM_SHA224	0x3000
/* SHA-256算法 */
#define NETCA_PKI_ALGORITHM_SHA256	0x4000
/* SHA-384算法 */
#define NETCA_PKI_ALGORITHM_SHA384	0x5000
/* SHA-512算法 */
#define NETCA_PKI_ALGORITHM_SHA512	0x6000
/* SM3算法 */
#define NETCA_PKI_ALGORITHM_SM3		0x7000
/* SHA-512/224算法 */
#define NETCA_PKI_ALGORITHM_SHA512_224	0x8000
/* SHA-512/256算法 */
#define NETCA_PKI_ALGORITHM_SHA512_256	0x9000
/* SHA3-224算法 */
#define NETCA_PKI_ALGORITHM_SHA3_224	0xA000
/* SHA3-256算法 */
#define NETCA_PKI_ALGORITHM_SHA3_256	0xB000
/* SHA3-384算法 */
#define NETCA_PKI_ALGORITHM_SHA3_384	0xC000
/* SHA3-512算法 */
#define NETCA_PKI_ALGORITHM_SHA3_512	0xD000

/* Mac算法 */
/* HMAC-MD5算法 */
#define NETCA_PKI_ALGORITHM_HMAC_MD5		0x20000
/* HMAC-SHA1算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA1		0x40000
/* HMAC-SHA224算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA224		0x60000
/* HMAC-SHA256算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA256		0x80000
/* HMAC-SHA384算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA384		0xA0000
/* HMAC-SHA512算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA512		0xC0000
/* SSL3使用MD5的Mac算法 */
#define NETCA_PKI_ALGORITHM_SSL3_MD5_MAC	0xE0000
/* HMAC-SM3算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SM3		0x100000
/* SSL3使用SHA1的Mac算法 */
#define NETCA_PKI_ALGORITHM_SSL3_SHA1_MAC	0x120000
/* HMAC-SHA512_224算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA512_224	0x140000
/* HMAC-SHA512_256算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA512_256	0x180000
/* ZUC的MAC算法 */
#define NETCA_PKI_ALGORITHM_ZUC_MAC			0x1A0000
/* AES-CMAC算法 */
#define NETCA_PKI_ALGORITHM_AES_CMAC		0x1C0000
/* TDES-CMAC算法 */
#define NETCA_PKI_ALGORITHM_3DES_CMAC		0x1E0000
/* SM4-CMAC算法 */
#define NETCA_PKI_ALGORITHM_SM4_CMAC		0x200000
/* AES-GMAC算法 */
#define NETCA_PKI_ALGORITHM_AES_GMAC		0x220000
/* HMAC-SHA3-224算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA3_224	0x240000
/* HMAC-SHA3-256算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA3_256	0x280000
/* HMAC-SHA3-384算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA3_384	0x2A0000
/* HMAC-SHA3-512算法 */
#define NETCA_PKI_ALGORITHM_HMAC_SHA3_512	0x2C0000

/* 对称加密算法 */
/* ECB模式的DES算法 */
#define NETCA_PKI_ALGORITHM_DES_ECB			0x400000
/* CBC模式的DES算法 */
#define NETCA_PKI_ALGORITHM_DES_CBC			0x800000
/* ECB模式的3DES算法 */
#define NETCA_PKI_ALGORITHM_3DES_ECB		0xC00000
/* ECB模式的3DES算法 */
#define NETCA_PKI_ALGORITHM_3DES_CBC		0x1000000
/* CTR模式的3DES算法 */
#define NETCA_PKI_ALGORITHM_3DES_CTR		0x1400000
/* ARC4算法 */
#define NETCA_PKI_ALGORITHM_ARC4			0x1800000
/* ECB模式的RC2算法 */
#define NETCA_PKI_ALGORITHM_RC2_ECB			0x1C00000
/* CBC模式的RC2算法 */
#define NETCA_PKI_ALGORITHM_RC2_CBC			0x2000000
/* ECB模式的AES算法 */
#define NETCA_PKI_ALGORITHM_AES_ECB			0x2400000
/* CBC模式的AES算法 */
#define NETCA_PKI_ALGORITHM_AES_CBC			0x2800000
/* CTR模式的AES算法 */
#define NETCA_PKI_ALGORITHM_AES_CTR			0x2C00000
/* ECB模式的SSF33算法 */
#define NETCA_PKI_ALGORITHM_SSF33_ECB		0x3000000
/* CBC模式的SSF33算法 */
#define NETCA_PKI_ALGORITHM_SSF33_CBC		0x3400000
/* CTR模式的SSF33算法 */
#define NETCA_PKI_ALGORITHM_SSF33_CTR		0x3800000
/* ECB模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_ECB			0x3C00000
/* CBC模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_CBC			0x4000000
/* CTR模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_CTR			0x4400000
/* ECB模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SMS4_ECB		0x4800000
/* CBC模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SMS4_CBC		0x4C00000
/* CTR模式的SMS4算法 */
#define NETCA_PKI_ALGORITHM_SMS4_CTR		0x5000000
/* ECB模式的SM4算法 */
#define NETCA_PKI_ALGORITHM_SM4_ECB			0x4800000
/* CBC模式的SM4算法 */
#define NETCA_PKI_ALGORITHM_SM4_CBC			0x4C00000
/* CTR模式的SM4算法 */
#define NETCA_PKI_ALGORITHM_SM4_CTR			0x5000000
/* ECB模式的SM1算法 */
#define NETCA_PKI_ALGORITHM_SM1_ECB_MOD		0x5400000
/* ZUC算法 */
#define NETCA_PKI_ALGORITHM_ZUC				0x5800000
/* 直接使用IV的ZUC算法 */
#define NETCA_PKI_ALGORITHM_ZUC_BASE		0x5C00000
/* AES-CCM */
#define NETCA_PKI_ALGORITHM_AES_CCM			0x6000000
/* SM4-CCM */
#define NETCA_PKI_ALGORITHM_SM4_CCM			0x6400000
/* AES-GCM */
#define NETCA_PKI_ALGORITHM_AES_GCM			0x6800000
/* AES-XTS */
#define NETCA_PKI_ALGORITHM_AES_XTS			0x6C00000
/* AES-CFB */
#define NETCA_PKI_ALGORITHM_AES_CFB			0x7000000
/* SM1-CFB */
#define NETCA_PKI_ALGORITHM_SM1_CFB			0x7400000
/* SM4-CFB */
#define NETCA_PKI_ALGORITHM_SM4_CFB			0x7800000
/* AES-OFB */
#define NETCA_PKI_ALGORITHM_AES_OFB			0x7C00000
/* SM1-OFB */
#define NETCA_PKI_ALGORITHM_SM1_OFB			0x8000000
/* SM4-OFB */
#define NETCA_PKI_ALGORITHM_SM4_OFB			0x8400000
/* AES-BC */
#define NETCA_PKI_ALGORITHM_AES_BC			0x8800000
/* AES-OFBNLF */
#define NETCA_PKI_ALGORITHM_AES_OFBNLF		0x8C00000
/* AES-FF1 */
#define NETCA_PKI_ALGORITHM_AES_FF1			0x9000000
/* SM4-FF1 */
#define NETCA_PKI_ALGORITHM_SM4_FF1			0x9400000
/* AES-FF3 */
#define NETCA_PKI_ALGORITHM_AES_FF3			0x9800000
/* SM4-FF3 */
#define NETCA_PKI_ALGORITHM_SM4_FF3			0x9C00000
/* SM4-GCM */
#define NETCA_PKI_ALGORITHM_SM4_GCM			0xA000000
/* AES-EAX */
#define NETCA_PKI_ALGORITHM_AES_EAX			0xA400000
/* SM4-EAX */
#define NETCA_PKI_ALGORITHM_SM4_EAX			0xA800000

/* 非对称算法 */
/* RSA算法 */
#define NETCA_PKI_ALGORITHM_RSA		1
/* DSA算法 */
#define NETCA_PKI_ALGORITHM_DSA		2
/* DH算法 */
#define NETCA_PKI_ALGORITHM_DH		3
/* ECC算法 */
#define NETCA_PKI_ALGORITHM_ECC		4
/* SM9 主密钥 */
#define NETCA_PKI_ALGORITHM_SM9_MASTER_KEY		5
/* SM9 用户密钥 */
#define NETCA_PKI_ALGORITHM_SM9_USER_KEY		6
/* 只能用于OAEP的RSA算法 */
#define NETCA_PKI_ALGORITHM_RSA_ONLY_OAEP	0x11
/* 只能用于PSS的RSA算法 */
#define NETCA_PKI_ALGORITHM_RSA_ONLY_PSS	0x21
/* 只能用于ECDH的ECC算法 */
#define NETCA_PKI_ALGORITHM_ECC_ONLY_ECDH	0x14
/* 只能用于ECMQV的ECC算法 */
#define NETCA_PKI_ALGORITHM_ECC_ONLY_ECMQV	0x24





/* 密钥对生成算法 */
/* RSA算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_RSA		1
/* DSA算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_DSA		2
/* DH算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_DH		3
/* ECC算法 */
#define NETCA_PKI_ALGORITHM_GENKEYPAIR_ECC		4

/* 非对称加密算法 */
/* PKCS#1 V1.5的RSA加密算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_V1_5_ENC		0x10
/* PKCS#1 OAEP的RSA加密算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_OAEP			0x20
/* 原始未填充的RSA加密算法 */
#define NETCA_PKI_ALGORITHM_RSA_RAW_ENC				0x30
/* SM2加密算法 */
#define NETCA_PKI_ALGORITHM_SM2_ENC					0x40
/* ECC的ECIES加密算法 */
#define NETCA_PKI_ALGORITHM_ECIES					0x50


/* 签名算法，只用于设备接口 */
/* PKCS#1 V1.5的RSA签名算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_V1_5_SIGN		0x100
/* PKCS#1 PSS的RSA签名算法 */
#define NETCA_PKI_ALGORITHM_RSA_PKCS1_PSS			0x200
/* 原始未填充的RSA签名算法 */
#define NETCA_PKI_ALGORITHM_RSA_RAW_SIGN			0x300
/* DSA签名算法 */
#define NETCA_PKI_ALGORITHM_DSA_SIGN				0x400
/* ECDSA签名算法 */
#define NETCA_PKI_ALGORITHM_ECDSA_SIGN				0x800
/* SM2签名算法 */
#define NETCA_PKI_ALGORITHM_SM2_SIGN				0x1000


/* 签名算法，用于应用程序 */
/* MD5WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_MD5WITHRSA				1
/* SHA1WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA1WITHRSA				2
/* SHA224WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA224WITHRSA			3
/* SHA256WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA256WITHRSA			4
/* SHA384WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA384WITHRSA			5
/* SHA512WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA512WITHRSA			6
/* MD5WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_MD5WITHRSA_NOHASHID		7
/* SHA1WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA1WITHRSA_NOHASHID	8
/* SHA224WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA224WITHRSA_NOHASHID	9
/* SHA256WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA256WITHRSA_NOHASHID	10
/* SHA384WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA384WITHRSA_NOHASHID	11
/* SHA512WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SHA512WITHRSA_NOHASHID	12
/* DSAWithSHA1 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA1				13
/* DSAWithSHA224 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA224			14
/* DSAWithSHA256 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA256			15
/* ECDSAWithSHA1 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA1			16
/* ECDSAWithSHA224 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA224			17
/* ECDSAWithSHA256 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA256			18
/* ECDSAWithSHA384 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA384			19
/* ECDSAWithSHA512 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA512			20
/* SSLV3使用的RSA签名 */
#define NETCA_PKI_ALGORITHM_SSL_RSA					21
/* RSA PSS 签名 */
#define NETCA_PKI_ALGORITHM_RSA_PSS					22
/* ECDSAWithSM3 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSM3			23
/* SM3WthRSA签名算法，但是只是对Hash值签名，不是DigestInfo */
#define NETCA_PKI_ALGORITHM_SM3WITHRSA_NOHASHID		24
/* SM3WithSM2 */
#define NETCA_PKI_ALGORITHM_SM3WITHSM2				25
/* SHA1WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA1WITHSM2				26
/* SH224WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA224WITHSM2			27
/* SH256WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA256WITHSM2			28
/* SH384WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA384WITHSM2			29
/* SH512WithSM2 */
#define NETCA_PKI_ALGORITHM_SHA512WITHSM2			30
/* SM3WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SM3WITHRSA				31
/* PKCS#1 V1.5的RSA签名算法，只用于NetcaPKICryptoSignHash和NetcaPKICryptoVerifyHash */
#define NETCA_PKI_ALGORITHM_RSASSA_PKCS1_V1_5		32
/* 非标准的SM3WithSM2，不用Z的 */
#define NETCA_PKI_ALGORITHM_SJS_SM3WITHSM2			33
/* SHA512_224WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA512_224WITHRSA		34
/* SHA512_256WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA512_256WITHRSA		35
/* SHA3-224WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA3_224WITHRSA			36
/* SHA3-256WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA3_256WITHRSA			37
/* SHA3-384WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA3_384WITHRSA			38
/* SHA3-512WthRSA签名算法 */
#define NETCA_PKI_ALGORITHM_SHA3_512WITHRSA			39
/* ECDSAWithSHA3-224 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA3_224		40
/* ECDSAWithSHA3-256 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA3_256		41
/* ECDSAWithSHA3-384 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA3_384		42
/* ECDSAWithSHA3-512 */
#define NETCA_PKI_ALGORITHM_ECDSAWITHSHA3_512		43
/* ECDSA，仅用于SignHash */
#define NETCA_PKI_ALGORITHM_ECDSA_SIGNHASH				44
/* DSA，仅用于SignHash */
#define NETCA_PKI_ALGORITHM_DSA_SIGNHASH					45
/* DSAWithSHA384 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA384			46
/* DSAWithSHA512 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA512			47
/* DSAWithSHA3_224 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA3_224			48
/* DSAWithSHA3_256 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA3_256			49
/* DSAWithSHA3_384 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA3_384			50
/* DSAWithSHA3_512 */
#define NETCA_PKI_ALGORITHM_DSAWITHSHA3_512			51
/* WAPI的ECDSAWithSHA256 */
#define NETCA_PKI_ALGORITHM_WAPI_ECDSA192WITHSHA256		52

/* 密钥协商算法 */
/* DH */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_DH			0x10000000
/* MQV */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_MQV		0x20000000
/* ECDH */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_ECDH		0x30000000
/* ECMQV */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_ECMQV		0x40000000
/* SM2 */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_SM2		0x50000000
/* ECC CDH */
#define NETCA_PKI_KEYAGREEMENT_ALGORITHM_ECC_CDH	0x60000000


#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA1		1
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA224	2
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA256	3
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA384	4
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA512	5
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA512_224	6
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA512_256	7
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA3_224	8
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA3_256	9
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA3_384	10
#define NETCA_PKI_MGF_ALGORITHM_PKCS1_MGF1SHA3_512	11

/* PKCS#5的PBKDF1，不推荐使用 */
#define NETCA_PKI_KDF_ALGORITHM_PKCS5_PBKDF1	1
/* PKCS#5的PBKDF2 */
#define NETCA_PKI_KDF_ALGORITHM_PKCS5_PBKDF2	2
/* PKCS#12的KDF */
#define NETCA_PKI_KDF_ALGORITHM_PKCS12			3
/* DH的KDF */
#define NETCA_PKI_KDF_ALGORITHM_DH_RFC2631		4
/* SM2的KDF */
#define NETCA_PKI_KDF_ALGORITHM_ECC_ANSI_X9_63	5
/* NIST SP800 56A的KDF */
#define NETCA_PKI_KDF_ALGORITHM_NIST_SP800_56A_SINGLE_STEP_KDF	6

/* 使用所有的UNCIDE字符，而不只是BMP */
#define NETCA_PKI_PKCS12_FLAG_USEALLUNICODE		1
/* 按照MS的方式进行截断 */
#define NETCA_PKI_PKCS12_FLAG_MSTRUN			2


/* 密码类型 */
/* 用户密码 */
#define NETCA_PKI_USER_PWD			1
/* 解锁密码 */
#define NETCA_PKI_SO_PWD			2
/* 超级密码 */
#define NETCA_PKI_SUPER_PWD			3
/* 应用密码 */
#define NETCA_PKI_APP_PWD_BASE		0x10000			


/* 不支持获取密码错误重试次数 */
#define NETCA_PKI_UNSUPPORTED_RETRY_NUMBER			-1


/* 密钥对类型 */
/* 加密密钥对 */
#define NETCA_PKI_KEYPAIRTYPE_ENCRYPT			1
/* 签名密钥对 */
#define NETCA_PKI_KEYPAIRTYPE_SIGNATURE			2
/* 密钥协商密钥对 */
#define NETCA_PKI_KEYPAIRTYPE_KEYAGREEMENT		3


/* ECC曲线类型 P192 */
#define NETCA_PKI_ECC_CURVE_P192			1

/* ECC曲线类型 P224 */
#define NETCA_PKI_ECC_CURVE_P224			2

/* ECC曲线类型 P256 */
#define NETCA_PKI_ECC_CURVE_P256			3

/* ECC曲线类型 P384 */
#define NETCA_PKI_ECC_CURVE_P384			4

/* ECC曲线类型 P521 */
#define NETCA_PKI_ECC_CURVE_P521			5

/* ECC曲线类型 WAPI规定的曲线 */
#define NETCA_PKI_ECC_CURVE_WAPI			6

/* ECC曲线类型 SM2推荐的曲线 */
#define NETCA_PKI_ECC_CURVE_SM2				7

/* ECC曲线类型 brainpoolP192r1 */
#define NETCA_PKI_ECC_CURVE_BRAINPOOL_P192	8

/* ECC曲线类型 brainpoolP224r1 */
#define NETCA_PKI_ECC_CURVE_BRAINPOOL_P224	9

/* ECC曲线类型 brainpoolP256r1 */
#define NETCA_PKI_ECC_CURVE_BRAINPOOL_P256	10

/* ECC曲线类型 brainpoolP320r1 */
#define NETCA_PKI_ECC_CURVE_BRAINPOOL_P320	11

/* ECC曲线类型 brainpoolP384r1 */
#define NETCA_PKI_ECC_CURVE_BRAINPOOL_P384	12

/* ECC曲线类型 brainpoolP512r1 */
#define NETCA_PKI_ECC_CURVE_BRAINPOOL_P512	13

/* ECC曲线类型 ANSSI ECC FRP256V1 */
#define NETCA_PKI_ECC_CURVE_FRP256V1		14

/* ECC曲线类型 SM9 */
#define NETCA_PKI_ECC_CURVE_SM9				15

/* ECC曲线类型 secp256k1 */
#define NETCA_PKI_ECC_CURVE_SECP256K1		16

/* 设备类型 */
/* 这个不是一个真正的设备类型，只是表示可以匹配任意的类型 */
#define NETCA_PKI_DEVICE_TYPE_ANY			-1
/* 内置的软件实现 */
#define NETCA_PKI_DEVICE_TYPE_BUILDIN_SOFTWARE		0
/* 明华EK-PK系列的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_EKPK		1
/* 明华版本2的EK-PKXC系列的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_EKPKXC_V2	2
/* 飞天epass3000 */
#define NETCA_PKI_DEVICE_TYPE_EPASS3000		3
/* 海泰的Key */
#define NETCA_PKI_DEVICE_TYPE_HAIKEY		4
/* 飞天epass3003 */
#define NETCA_PKI_DEVICE_TYPE_EPASS3003		5
/* 明华版本3的EK-PKXC系列的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_EKPKXC_V3		6
/* 明华文鼎创EKey */
#define NETCA_PKI_DEVICE_TYPE_MWESKEY	7
/* 微柏的Key */
#define NETCA_PKI_DEVICE_TYPE_WEEPAL 	8
/* 飞天502的卡 */
#define NETCA_PKI_DEVICE_TYPE_FT502 	9
/* 飞天SM2的Key */
#define NETCA_PKI_DEVICE_TYPE_FEITIAN_SM2 	10
/* OPENSSL软设备 */
#define NETCA_PKI_DEVICE_TYPE_OPENSSL 	11
/* 天翼税通上海普华COS */
#define NETCA_PKI_DEVICE_TYPE_ETAX		30
/* 天翼税通华为COS */
#define NETCA_PKI_DEVICE_TYPE_HWETAX		31
/* 南方基地ECC设备 */
#define NETCAPKI_DEVICE_TYPE_ECCEKEY_CISIP	32
/* 海泰的SM2的Key */
#define NETCA_PKI_DEVICE_TYPE_HAIKEY_SM2	33
/* UIM Key */
#define NETCA_PKI_DEVICE_TYPE_UIMKEY		34
/* HD Micro SD Key */
#define NETCA_PKI_DEVICE_TYPE_HDSDKEY		35
/* 渔翁SJK Key*/
#define NETCA_PKI_DEVICE_TYPE_FMSJK		36
/* 天翼税通浪潮COS */
#define NETCA_PKI_DEVICE_TYPE_INSPURETAX		37
/* VAST虚拟设备 */
#define NETCA_PKI_DEVICE_TYPE_VAST			99
/* 得安的SJY05B加密机 */
#define NETCA_PKI_DEVICE_TYPE_SJY05B		100
/* 得安的SJY03B加密卡 */
#define NETCA_PKI_DEVICE_TYPE_SJY03B		101
/* 得安的SJJ0929加密机 */
#define NETCA_PKI_DEVICE_TYPE_SJJ0929	102
/* 普华SJJ1011加密机 */
#define NETCA_PKI_DEVICE_TYPE_SJJ1011	103
/* 渔翁加密卡 */
#define NETCA_PKI_DEVICE_TYPE_SJK0810		104
/* GDCA明华二版的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_GDCAEKPKXC_V2 401
/* GDCA明华三版的EKey */
#define NETCA_PKI_DEVICE_TYPE_EKEY_GDCAEKPKXC_V3 402
/* GDCA握奇的EKey */
#define NETCA_PKI_DEVICE_TYPE_GDCAWATCHKEY		403
/* SZCA飞天3003 */
#define NETCA_PKI_DEVICE_TYPE_SZCAEPASS3003		421

/* 设备类别 */
#define NETCA_DEVICE_CLASS_UNKNOWN		0
#define NETCA_DEVICE_CLASS_USB			1
#define NETCA_DEVICE_CLASS_PCI			2
#define NETCA_DEVICE_CLASS_NETWORK		3
#define NETCA_DEVICE_CLASS_COM			4
#define NETCA_DEVICE_CLASS_BUILDIN		5
#define NETCA_DEVICE_CLASS_PCSC			6
#define NETCA_DEVICE_CLASS_ICCARD		7
#define NETCA_DEVICE_CLASS_SOFTWARE		8

#define NETCA_PKI_DEVICE_FLAG_SILENT					1
#define NETCA_PKI_DEVICE_FLAG_CACHE_PIN_IN_PROCESS		(0<<1)
#define NETCA_PKI_DEVICE_FLAG_CACHE_PIN_IN_HANDLE		(1<<1)
#define NETCA_PKI_DEVICE_FLAG_NOT_CACHE_PIN				(2<<1)
#define NETCA_PKI_DEVICE_FLAG_CAN_INSTALL_CERT			0x100
#define NETCA_PKI_DEVICE_FLAG_SHARE						0x1000





#define NETCA_PKI_BASE64_NO_NL		1
#define NETCA_PKI_BASE64_STRICT		2
#define NETCA_PKI_BASE64_NOPADDING		0x80
#define NETCA_PKI_BASE64_URL			0x100

/* 最大可能的分组加密的分组长度，值定义错了，但却不能再修改了 */
#define NETCA_PKI_CRYPT_BLOCK_MAXLEN	256

#define NETCA_PKI_PADDING_NONE		1
#define NETCA_PKI_PADDING_PKCS5		2
#define NETCA_PKI_PADDING_PKCS7		2


#define NETCA_PKI_CERT_ENCODE_DER				1
#define NETCA_PKI_CERT_ENCODE_BASE64			2
#define NETCA_PKI_CERT_ENCODE_BASE64_NO_NL		3

#define NETCA_PKI_CERT_ATTRIBUTE_PRIVKEY_ATTRIBUTE			1
#define NETCA_PKI_CERT_ATTRIBUTE_VERSION					2
#define NETCA_PKI_CERT_ATTRIBUTE_SIGNALGO					3
#define NETCA_PKI_CERT_ATTRIBUTE_PUBKEYALGO					4
#define NETCA_PKI_CERT_ATTRIBUTE_PUBKEYBITS					5
#define NETCA_PKI_CERT_ATTRIBUTE_KEYUSAGE					6
#define NETCA_PKI_CERT_ATTRIBUTE_HAS_PRIVKEY_ATTRIBUTE		7
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER						8
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_DISPLAY_NAME		9
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_C					10
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_O					11
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_OU					12
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_CN					13
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_EMAIL				14
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT					15
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_DISPLAY_NAME		16
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_C					17
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_O					18
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_OU					19
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_CN					20
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_EMAIL				21
#define NETCA_PKI_CERT_ATTRIBUTE_EX_FRIENDLY_NAME			22
#define NETCA_PKI_CERT_ATTRIBUTE_EX_NAME					23
#define NETCA_PKI_CERT_ATTRIBUTE_EX_ORGANIZATION			24
#define NETCA_PKI_CERT_ATTRIBUTE_EX_DEPARTMENT				25
#define NETCA_PKI_CERT_ATTRIBUTE_EX_EMAIL					26
#define NETCA_PKI_CERT_ATTRIBUTE_GET_KEYPAIR_HADNLE_NEED_PWD		27
#define NETCA_PKI_CERT_ATTRIBUTE_KEYPAIR_HADNLE				28
#define NETCA_PKI_CERT_ATTRIBUTE_PREVCERT_THUMBPRINT		29
#define NETCA_PKI_CERT_ATTRIBUTE_VALIDITY_START				30
#define NETCA_PKI_CERT_ATTRIBUTE_VALIDITY_END				31
/* 十进制证书序列号 */
#define NETCA_PKI_CERT_ATTRIBUTE_SN_DEC						32
/* 十六进制证书序列号 */
#define NETCA_PKI_CERT_ATTRIBUTE_SN_HEX						33
#define NETCA_PKI_CERT_ATTRIBUTE_IN_VALIDITY				34
#define NETCA_PKI_CERT_ATTRIBUTE_PRIVATE_ISCSP				35
#define NETCA_PKI_CERT_ATTRIBUTE_UPN						36
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_ST					37
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_L					38
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_ST					39
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_L					40
#define NETCA_PKI_CERT_ATTRIBUTE_EX_DEVICE_TYPE				41
#define NETCA_PKI_CERT_ATTRIBUTE_EX_DEVICE_SN				42
#define NETCA_PKI_CERT_ATTRIBUTE_PUBKEY_ECC_CURVE			43
#define NETCA_PKI_CERT_ATTRIBUTE_THUMBPRINT					44
#define NETCA_PKI_CERT_ATTRIBUTE_HASH_ISSUER				45
#define NETCA_PKI_CERT_ATTRIBUTE_HASH_SUBJECT				46
#define NETCA_PKI_CERT_ATTRIBUTE_HASH_PUBKEY				47
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_LDAP_NAME			48
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_XMLSIG_NAME			49
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_LDAP_NAME			50
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_XMLSIG_NAME		51
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_HEX_ENCODE			52
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_HEX_ENCODE			53
#define NETCA_PKI_CERT_ATTRIBUTE_CHECK_PRIVKEY				54
#define NETCA_PKI_CERT_ATTRIBUTE_CSP_NAME					55
#define NETCA_PKI_CERT_ATTRIBUTE_CRL_URL					56
#define NETCA_PKI_CERT_ATTRIBUTE_DELTA_CRL_URL				57
#define NETCA_PKI_CERT_ATTRIBUTE_OCSP_URL					58
#define NETCA_PKI_CERT_ATTRIBUTE_IP							59
#define NETCA_PKI_CERT_ATTRIBUTE_DNS_NAME					60
#define NETCA_PKI_CERT_ATTRIBUTE_CERT_POLICY_OID			61
#define NETCA_PKI_CERT_ATTRIBUTE_EXTENDED_KEY_USAGE			62
#define NETCA_PKI_CERT_ATTRIBUTE_HASH_SUBJECT_PUBKEY_INFO	63
#define NETCA_PKI_CERT_ATTRIBUTE_EX_VERIFYCERT_PARAM		64
#define NETCA_PKI_CERT_ATTRIBUTE_SMIMECAPABILITIES			65
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_KEYID				66
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_DN_QUALIFIER		67
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_DN_QUALIFIER		68
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_SN					69
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_SN					70
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_TITLE				71
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_TITLE				72
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_SURNAME				73
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_SURNAME			74
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_GIVEN_NAME			75
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_GIVEN_NAME			76
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_INITIALS			77
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_INITIALS			78
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_PSEUDONYM			79
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_PSEUDONYM			80
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_GENERATION_QUALIFIER	81
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_GENERATION_QUALIFIER	82			
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_DC					83
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_DC					84
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_UID					85
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_UID				86			
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_STREET				87
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_STREET				88
#define NETCA_PKI_CERT_ATTRIBUTE_CAISSUERS_URL				89
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_JURISDICTION_L		90
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_JURISDICTION_ST	91
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_JURISDICTION_C		92
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_BUSINESS_CATEGORY	93
#define NETCA_PKI_CERT_ATTRIBUTE_GB_IDENTITY_CODE			94
#define NETCA_PKI_CERT_ATTRIBUTE_CRICAL_EXTENSIONS			95
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_AND_SERIALNUMBER	96
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_REVERSE				97
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_REVERSE			98
#define NETCA_PKI_CERT_ATTRIBUTE_CERT_CLASS					99
#define NETCA_PKI_CERT_ATTRIBUTE_CERT_CLASS_EXT_VALUE		100
#define NETCA_PKI_CERT_ATTRIBUTE_SHENZHEN_SUBJECT_UNIQUE_ID	101
#define NETCA_PKI_CERT_ATTRIBUTE_NETCA_SUBJECT_UNIQUE_ID	102
#define NETCA_PKI_CERT_ATTRIBUTE_KEYPAIR_INFO_STRING		103
#define NETCA_PKI_CERT_ATTRIBUTE_USER_CERT_SERVICE_ID		104
#define NETCA_PKI_CERT_ATTRIBUTE_IDENTIFY_ITEMS				105
#define NETCA_PKI_CERT_ATTRIBUTE_ENTERPRISEID_ITEMS			106
#define NETCA_PKI_CERT_ATTRIBUTE_RSAPSS_PARAM				107
#define NETCA_PKI_CERT_ATTRIBUTE_CAREPOSITORY_URL			108
#define NETCA_PKI_CERT_ATTRIBUTE_TIMESTAMPING_URL			109
#define NETCA_PKI_CERT_ATTRIBUTE_EX_EXTRA_INFO				110
#define NETCA_PKI_CERT_ATTRIBUTE_REGISTEREDID				111
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_TELEPHONE_NUMBER			112
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_TELEPHONE_NUMBER			113
#define NETCA_PKI_CERT_ATTRIBUTE_ISSUER_ORGANIZATION_IDENTIFIER		114
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_ORGANIZATION_IDENTIFIER	115
#define NETCA_PKI_CERT_ATTRIBUTE_OCSP_REQ_ENCODE			116
#define NETCA_PKI_CERT_ATTRIBUTE_OCSP_REQ_ENCODE_NO_NONCE	117
#define NETCA_PKI_CERT_ATTRIBUTE_ENTITY_UNIQUE_ID			118
#define NETCA_PKI_CERT_ATTRIBUTE_ISCA						119
#define NETCA_PKI_CERT_ATTRIBUTE_USER_NOTICE_EXPLICIT_TEXT	120
#define NETCA_PKI_CERT_ATTRIBUTE_SUBJECT_PUBKEY_INFO_HEX_ENCODE	121
#define NETCA_PKI_CERT_ATTRIBUTE_PUBKEY_HEX_ENCODE				122

/* 自签证书 */
#define NETCA_PKI_CERT_CLASS_SELFSIGN						1
/* 自颁发证书 */
#define NETCA_PKI_CERT_CLASS_SELFISSUER						2
/* CA证书 */
#define NETCA_PKI_CERT_CLASS_CA								3
/* TSA证书 */
#define NETCA_PKI_CERT_CLASS_TSA							4
/* OCSP证书 */
#define NETCA_PKI_CERT_CLASS_OCSP							5
/* 机构证书 */
#define NETCA_PKI_CERT_CLASS_ORGANIZATION					6
/* 单位员工证书 */
#define NETCA_PKI_CERT_CLASS_EMPLOYEE	 					8
/* 自然人证书 */
#define NETCA_PKI_CERT_CLASS_INDIVIDUAL	 					9
/* 服务器证书 */
#define NETCA_PKI_CERT_CLASS_SERVER	 						10
/* S/MIME证书 */
#define NETCA_PKI_CERT_CLASS_SMIME	 						11
/* 代码签名证书 */
#define NETCA_PKI_CERT_CLASS_CODESIGN 						12
/* 其他证书 */
#define NETCA_PKI_CERT_CLASS_OTHER							0


/* 整数类型 */
#define NETCA_PKI_CERT_ATTRIBUTE_TYPE_INT					1
/* 单值字符串类型 */
#define NETCA_PKI_CERT_ATTRIBUTE_TYPE_SINGLE_VALUE_STRING	2
/* 多值字符串类型 */
#define NETCA_PKI_CERT_ATTRIBUTE_TYPE_MULTI_VALUE_STRING	3
/* Hash类型 */
#define NETCA_PKI_CERT_ATTRIBUTE_TYPE_HASH					4



#define NETCA_PKI_SEARCH_KEYPAIR_FLAG_DEVICE				0x10000000
#define NETCA_PKI_SEARCH_KEYPAIR_FLAG_LOCAL_MACHINE			0x20000000
#define NETCA_PKI_SEARCH_KEYPAIR_FLAG_CURRENT_USER			0x40000000

#define NETCA_PKI_CERT_PURPOSE_ENCRYPT			1
#define NETCA_PKI_CERT_PURPOSE_SIGN				2
#define NETCA_PKI_CERT_PURPOSE_KEYAGREEMENT		4
#define NETCA_PKI_CERT_PURPOSE_VERIFY_OLD_DATA	0x10000002
#define NETCA_PKI_CERT_PURPOSE_DECRYPT_WITH_OLD_CERT	0x10000001


#define NETCA_PKI_USAGE_ENCRYPT			1
#define NETCA_PKI_USAGE_DECRYPT			2
#define NETCA_PKI_USAGE_HASH			3
#define NETCA_PKI_USAGE_MAC				4
#define NETCA_PKI_USAGE_SIGN			5
#define NETCA_PKI_USAGE_VERIFY			6
#define NETCA_PKI_USAGE_GENKEYPAIR		7
#define NETCA_PKI_USAGE_KEYAGREEMENT	8
#define NETCA_PKI_USAGE_IMPORTKEY_FOR_ENCRYPT	9
#define NETCA_PKI_USAGE_IMPORTKEY_FOR_DECRYPT	10
#define NETCA_PKI_USAGE_IMPORTKEYPAIR	11


#define NETCA_PKI_CERT_VERSION_V1			0
#define NETCA_PKI_CERT_VERSION_V2			1
#define NETCA_PKI_CERT_VERSION_V3			2


#define NETCA_PKI_CERT_TYPE_LOCAL_MACHINE		0x8000

#define NETCA_PKI_CERT_STORE_TYPE_CURRENT_USER		0
#define NETCA_PKI_CERT_STORE_TYPE_LOCAL_MACHINE		1
#define NETCA_PKI_CERT_STORE_TYPE_MEMORY			2

#define NETCA_PKI_CERT_STORE_NAME_MY		"my"
#define NETCA_PKI_CERT_STORE_NAME_OTHERS	"others"
#define NETCA_PKI_CERT_STORE_NAME_CA		"ca"
#define NETCA_PKI_CERT_STORE_NAME_ROOT		"root"
#define NETCA_PKI_CERT_STORE_NAME_DEVICE	"device"
#define NETCA_PKI_CERT_STORE_NAME_DISALLOWED	"disallowed"



#define NETCA_PKI_CERTVERIFY_OPTION_USEV1CERT			0x1
#define NETCA_PKI_CERTVERIFY_OPTION_USEALLCACERT		0x2
#define NETCA_PKI_CERTVERIFY_OPTION_IGNOREALLEXT		0x4
#define NETCA_PKI_CERTVERIFY_OPTION_VERIFYEEREVOKE		0x8
#define NETCA_PKI_CERTVERIFY_OPTION_VERIFYCAREVOKE		0x10
#define NETCA_PKI_CERTVERIFY_OPTION_ONLINE_GETCACERT	0x20
#define NETCA_PKI_CERTVERIFY_OPTION_ONLINE_GETREVOKEINFO	0x40
#define NETCA_PKI_CERTVERIFY_OPTION_NOT_VERIFY_TIME		0x80
#define NETCA_PKI_CERTVERIFY_OPTION_CHECK_AKID			0x100
#define NETCA_PKI_CERTVERIFY_OPTION_USE_GSMA_NAMECONSTRAINTS		0x200
#define NETCA_PKI_CERTVERIFY_OPTION_USE_SYSTEM_CERT_STORE		0x800

#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_DESCBC		1
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_RC2CBC		2
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_TDESCBC		3
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_AES128CBC		4
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_AES192CBC		5
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_AES256CBC		6
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SSF33CBC		7
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SM1CBC		8
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SMS4CBC		9
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_SM4CBC		9
#define NETCA_PKI_ENVELOPEDDATA_ALGORITHM_RC4			10

#define NETCA_PKI_ENVELOPEDDATA_FLAG_USEKEYID			1



#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_ENC_ALGORITHM			1
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_HAS_CONTENT_INFO		2
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_USE_SM2_Q7			3
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_USE_SM2_Q7_VERSION1	4
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_USE_RFC3278			5
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_USE_UKM				6
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_DONT_DECRYPT			7
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_AESWRAP_HAS_PARAM		8
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_RSA_OAEP_PARAM		9
#define NETCA_PKI_ENVELOPEDDATA_ATTRIBUTE_USE_GMSM4_OID			10

#define NETCA_PKI_ENVELOPEDDATA_CONFIG_ATTRIBUTE_USE_SUBJECT_KEYID		0x100



#define NETCA_PKI_ENVELOPEDDATA_RECIPENTID_ISSUER_AND_SERIALNUMBER		1
#define NETCA_PKI_ENVELOPEDDATA_RECIPENTID_SUBJECT_KEYID				2


#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_REVOKE				1
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_ONLINE					2
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_CACERT_REVOKE		4
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_OCSP				0x10
#define NETCA_PKI_CERTIFICATE_VERIFY_FLAG_VERIFY_CRL				0x20


#define NETCA_PKI_CERTIFICATE_STATUS_UNREVOKED						1
#define NETCA_PKI_CERTIFICATE_STATUS_UNDETERMINED					-1
#define NETCA_PKI_CERTIFICATE_STATUS_REVOKED						0
#define NETCA_PKI_CERTIFICATE_STATUS_CA_REVOKED                     -2

#define NETCA_PKI_CRL_REASON_UNSPECIFIED				0
#define NETCA_PKI_CRL_REASON_KEYCOMPROMISE				1
#define NETCA_PKI_CRL_REASON_CACOMPROMISE				2
#define NETCA_PKI_CRL_REASON_AFFILIATION_CHANGED		3
#define NETCA_PKI_CRL_REASON_SUPERSEDED					4
#define NETCA_PKI_CRL_REASON_CESSATION_OF_OPERATION		5
#define NETCA_PKI_CRL_REASON_CERTIFATE_HOLD				6
#define NETCA_PKI_CRL_REASON_REMOVE_FROM_CRL			8
#define NETCA_PKI_CRL_REASON_PRIVILEGE_WITHDRAWN		9
#define NETCA_PKI_CRL_REASON_AACOMPROMISE				10

#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNER_COUNT					1
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_DETACHED						2
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGN_ALGO					3
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SIGNINGTIME				4
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_CONTENT_INFO				5
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_KEYID					6
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_INCLUDE_CERT_OPTION			7
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_KEEP_TBS						8
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SIGNINGCERT				9
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNINGCERTV2_HASH_ALGO		10
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNINGTIME					11
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TSATIME						12
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CONTENT_OID					13
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_VALIDITY				14
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_TSATIME					15
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TIMESTAMP_SERIAL_NUMBER		16
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TIMESTAMP_POLICY				17
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_TIMESTAMP_HASH_ALGO			18
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COUNTERSIGNATURE_COUNT		19
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNEDATTRS_COUNT			20
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_UNSIGNEDATTRS_COUNT			21
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNATURE_VALUE				22
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SM2_Q7					23
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SM2SIGN_OID				24
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_PKCS7					25
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_RESULT				26
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_NOHASHID_SIGNATURE	27
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNERINFO_VALUE				28
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SMIMECAPABILITIES			29
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_NOTDERSM2SIGNATURE			30
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CONTENT_HINTS				31
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CONTENT_IDENTIFIER			32
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CONTENT_REFERENCE			33
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COMMITMENT_TYPE_INDICATION	34
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNER_LOCATION				35
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_MIME_TYPE					36
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNATURE_POLICYID			37
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_CONTENT_TIMESTAMP		38
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_COMPLETE_CERTIFICATE_REFS	39
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COMPLETE_CERTIFICATE_REFS_CERT_COUNT	40
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_LEVEL					41
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_PARAM					42
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFYCERT_RESULT			43
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFYCERT_STATUS			44
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFYCERT_REVOKE_REASON		45
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFYCERT_REVOKE_TIME		46
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CHECK_COMPLETE_CERT_REFS		47
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CHECK_COMPLETE_REVOCATION_REFS		48
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CHECK_CERT_VALUES			49
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CHECK_REVOCATION_VALUES		50
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_COMPLETE_REVOCATION_REFS	51
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_CERT_VALUES				52
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_REVOCATION_VALUES		53
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_SYSTEM_CERTSTORE_VERIFY	54
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COMPLETE_CERTIFICATE_REFS	55
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COMPLETE_REVOCATION_REFS		56
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNINGCERT_ATTRIBUTE		57
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_SIGNINGCERTV2_ATTRIBUTE		58
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CONTENT_HINTS_IS_SIGNED_ATTRIBUTE	59
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CONTENT_IDENTIFIER_IS_SIGNED_ATTRIBUTE	60
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_ESC_TIMESTAMP_COUNT			61
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CERTCRL_TIMESTAMP_COUNT		62
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_ARCHIVE_TIMESTAMP_V2_COUNT	63
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_ATS_HASH_INDEX				65
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_ARCHIVE_TIMESTAMP_V3_COUNT	66
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_CHECK_ATS_HASH_INDEX			67
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HAS_ADBE_REVOCATIONINFO_ARCHIVAL			68
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_ADBE_REVOCATIONINFO_ARCHIVAL_IS_EMPTY		69
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_OCSP_VACERT_INFO				70
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_RSAPSS_PARAM					71
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COUNTERSIGNATURE_RSAPSS_PARAM		72
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_RSAENCRYPTION_OID		73
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_ATS_HASH_INDEX_INDEX			74
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_ARCHIVE_TIMESTAMP_V3_INDEX	74
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_IS_ATS_HASH_INDEX_V3			75
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_HASH_ALGO					76
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_TIME					77
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_COUNTERSIGNATURE_VERIFY_TIME	78
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_USE_ALGORITHM_PROTECTION		79
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_PARAM_ONLINE_GET_CA_CERT		80
#define NETCA_PKI_SIGNEDDATA_ATTRIBUTE_VERIFY_PARAM_ONLINE_GET_REVOKE_INFO	81


#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_NONE				1
#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_SELF				2
#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_CERTPATH			3
#define NETCA_PKI_SIGNEDDATA_INCLUDE_CERT_OPTION_CERTPATHWITHROOT	4


#define NETCA_PKI_SIGNEDDATA_ADDOCSP_IN_REVOCATIONINFOCHOICE		1


#define NETCA_PKI_SIGNEDDATA_VERIFY_LEVEL_NO_VERIFY					0
#define NETCA_PKI_SIGNEDDATA_VERIFY_LEVEL_VERIFY_SIGNATURE_ONLY		1
#define NETCA_PKI_SIGNEDDATA_VERIFY_LEVEL_VERIFY_CERT				2
#define NETCA_PKI_SIGNEDDATA_VERIFY_LEVEL_VERIFY_CERT_REVOKE		3
#define NETCA_PKI_SIGNEDDATA_VERIFY_LEVEL_VERIFY_CERTPATH_REVOKE	4


#define NETCA_PKI_SIGNEDDATA_SIGNERID_ISSUER_AND_SERIALNUMBER		1
#define NETCA_PKI_SIGNEDDATA_SIGNERID_SUBJECT_KEYID					2

#define NETCA_PKI_SIGNEDDATA_CADES_ATS_HASH_INDEX_TYPE		0
#define NETCA_PKI_SIGNEDDATA_CADES_ATS_HASH_INDEX_V3_TYPE	1


#define NETCA_PKI_KEYUSAGE_DIGITALSIGNATURE				(1<<0)
#define NETCA_PKI_KEYUSAGE_NONREPUDIATION				(1<<1)
#define NETCA_PKI_KEYUSAGE_CONTENTCOMMITMENT			(1<<1)
#define NETCA_PKI_KEYUSAGE_KEYENCIPHERMENT				(1<<2)
#define NETCA_PKI_KEYUSAGE_DATAENCIPHERMENT				(1<<3)
#define NETCA_PKI_KEYUSAGE_KEYAGREEMENT					(1<<4)
#define NETCA_PKI_KEYUSAGE_KEYCERTSIGN					(1<<5)
#define NETCA_PKI_KEYUSAGE_CRLSIGN						(1<<6)
#define NETCA_PKI_KEYUSAGE_ENCIPHERONLY					(1<<7)
#define NETCA_PKI_KEYUSAGE_DECIPHERONLY					(1<<8)


#define NETCA_PKI_DATA_ID_COMMON_BASE		0x100

#define NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_NAME				0
#define NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_FRIENDLY_NAME		1
#define	NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_ORGANIZATION		2
#define	NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_DEPARTMENT			3
#define	NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_EMAIL				4
#define NETCA_PKI_ADDRESSBOOK_SEARCHTYPE_PHONE			5

/* 联系人属性类型 */
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_ENCCERT		0
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_SIGNCERT		1
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_FRIENDLYNAME		2
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_ORGANIZATION		3
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_DEPARTMENT		4
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_EMAIL		5
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_PHONE		6
#define NETCA_PKI_ADDRESSBOOK_PERSONATTR_COMMENT		7

#define	NETCA_PKI_PROMTMSG_FLAG_NO_ARGUMENT			0
#define	NETCA_PKI_PROMTMSG_FLAG_ONE_ARGUMENT		1


#define NETCA_PKI_TIMESTAMP_RESP_STATUS_BADRESP					-1
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_BADTSACERT				-2
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_ACCESSDENIED			-3
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_GRANTED   				0
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_GRANTEDWITHMODS			1
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_REJECTION				2
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_WAITING					3
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_REVOCATIONWARNING		4
#define NETCA_PKI_TIMESTAMP_RESP_STATUS_REVOCATIONNOTIFICATION	5


#define NETCA_PKI_TIMESTAMP_NONCE_FLAG_NONE		1
#define NETCA_PKI_TIMESTAMP_NONCE_FLAG_RANDOM	2
#define NETCA_PKI_TIMESTAMP_NONCE_FLAG_FIX		3

#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_BADALG					(1<<0)
#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_BADREQUEST				(1<<2)
#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_BADDATAFORMAT			(1<<5)
#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_TIMENOTAVAILABLE		(1<<14)
#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_UNACCEPTEDPOLICY		(1<<15)
#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_UNACCEPTEDEXTENSION	(1<<16)
#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_ADDINFONOTAVAILABLE	(1<<17)
#define NETCA_PKI_TIMESTAMP_PKI_FAILURE_INFO_SYSTEMFAILURE			(1<<25)

#define NETCA_PKI_CERTREQ_VERSION					1
#define NETCA_PKI_CERTREQ_SIGN_ALGO					2
#define NETCA_PKI_CERTREQ_SUBJECT					3
#define NETCA_PKI_CERTREQ_SUBJECT_REVERSE			4
#define NETCA_PKI_CERTREQ_SUBJECT_C					5
#define NETCA_PKI_CERTREQ_SUBJECT_ST				6
#define NETCA_PKI_CERTREQ_SUBJECT_L					7
#define NETCA_PKI_CERTREQ_SUBJECT_O					8
#define NETCA_PKI_CERTREQ_SUBJECT_OU				9
#define NETCA_PKI_CERTREQ_SUBJECT_CN				10
#define NETCA_PKI_CERTREQ_SUBJECT_EMAIL				11
#define NETCA_PKI_CERTREQ_SUBJECT_MULTI_OU			12
#define NETCA_PKI_CERTREQ_SUBJECT_MULTI_CN			13
#define NETCA_PKI_CERTREQ_SUBJECT_ENCODE_PARAM		14
#define NETCA_PKI_CERTREQ_ATTRIBUTE_COUNT			15
#define NETCA_PKI_CERTREQ_ATTRIBUTE_SMIMECAPABILITIES			16

/* 旧的个性化信息的ID */
#define NETCA_PKI_DATAID_OLD_CUSTOMINFO				999

#define NETCA_PKI_EXTENSION_TYPE_OCTETSTRING			1
#define NETCA_PKI_EXTENSION_TYPE_OID					2
#define NETCA_PKI_EXTENSION_TYPE_UTF8STRING				3
#define NETCA_PKI_EXTENSION_TYPE_NUMERICSTRING			4
#define NETCA_PKI_EXTENSION_TYPE_PRINTABLESTRING		5
#define NETCA_PKI_EXTENSION_TYPE_TELETEXSTRING			6
#define NETCA_PKI_EXTENSION_TYPE_VIDEOTEXSTRING			7
#define NETCA_PKI_EXTENSION_TYPE_IA5STRING				8
#define NETCA_PKI_EXTENSION_TYPE_GRAPHICSTRING			9
#define NETCA_PKI_EXTENSION_TYPE_VISIBLESTRING			10
#define NETCA_PKI_EXTENSION_TYPE_GENERALSTRING			11
#define NETCA_PKI_EXTENSION_TYPE_UNIVERSALSTRING		12
#define NETCA_PKI_EXTENSION_TYPE_BMPSTRING				13


#define NETCA_PKI_ENCKEYPAIR_TYPE_NONE			0
#define NETCA_PKI_ENCKEYPAIR_TYPE_3				1
#define NETCA_PKI_ENCKEYPAIR_TYPE_06			2
#define NETCA_PKI_ENCKEYPAIR_TYPE_PUHUA			3
#define NETCA_PKI_ENCKEYPAIR_TYPE_GDKM			4
#define NETCA_PKI_ENCKEYPAIR_TYPE_GDKM_2		5
#define NETCA_PKI_ENCKEYPAIR_TYPE_GBT_35276     5

#define NETCA_PKI_INSTALLCERT_FLAG_RESERVE_ENC_CERT			0x100
#define NETCA_PKI_INSTALLCERT_FLAG_RESERVE_SIGN_CERT		0x200
#define NETCA_PKI_INSTALLCERT_FLAG_DEL_DUP_ENC_KEYPAIR		0x400


#define NETCA_PKI_CONFIGNURE_STORE_FLAG_RESTORE		2
#define NETCA_PKI_CONFIGNURE_STORE_FLAG_ADDTEMP		1
#define NETCA_PKI_CONFIGNURE_STORE_FLAG_REPLACE		0


#define NETCA_PKI_HTTP_BASIC_AUTH		1
#define NETCA_PKI_HTTP_DIGEST_AUTH		2


#define NETCA_PKI_AUTHENTICODE_FLAG_DONTBUILDCERTPATH	0x10
#define NETCA_PKI_AUTHENTICODE_FLAG_INDIVIDUAL_CODESIGNING	0x1
#define NETCA_PKI_AUTHENTICODE_FLAG_COMMERCIAL_CODESIGNING	0x2
#define NETCA_PKI_AUTHENTICODE_FLAG_RFC3161_TIMESTAMP	0x80
#define NETCA_PKI_AUTHENTICODE_FLAG_ADD_SIGNATURE	0x100


#define NETCA_PKI_SMIME_ENCRYPKEY_PREF_TYPE_ISSUER_SN			0
#define NETCA_PKI_SMIME_ENCRYPKEY_PREF_TYPE_RECIPIENT_KEYID		1
#define NETCA_PKI_SMIME_ENCRYPKEY_PREF_TYPE_SUBJKEYID			2

#define NETCA_PKI_SMIME_ENCRYPKEY_PREF_TYPE_ADD_MSTYPE			0x80

/* 原子类型 */
#define NETCA_PKI_MIME_TYPE_BASIC			0
/* multipart */
#define NETCA_PKI_MIME_TYPE_MULTIPART		1
/* message */
#define NETCA_PKI_MIME_TYPE_MESSAGE			2

#define NETCA_PKI_MIME_HEADER_EXTS_ENCODE_Q			1
#define NETCA_PKI_MIME_HEADER_EXTS_ENCODE_B			2


#define NETCA_PKI_LDAP_FLAG_USETLS					0x8000
#define NETCA_PKI_LDAP_FLAG_DEREF_NEVER				0
#define NETCA_PKI_LDAP_FLAG_DEREF_INSEARCHING		1
#define NETCA_PKI_LDAP_FLAG_DEREF_FINDINGBASEOBJ	2
#define NETCA_PKI_LDAP_FLAG_DEREF_ALWAYS			3

#define NETCA_PKI_LDAP_SCOPE_BASEOBJECT		0
#define NETCA_PKI_LDAP_SCOPE_SINGLELEVEL	1		
#define NETCA_PKI_LDAP_SCOPE_WHOLESUBTREE	2



#define NETCA_PKI_CRLOCSPREF_FLAG_USE_CRL	1
#define NETCA_PKI_CRLOCSPREF_FLAG_USE_OCSP	2
#define NETCA_PKI_CRLOCSPREF_FLAG_HAS_CRLIDENTIFIER	4
#define NETCA_PKI_CRLOCSPREF_FLAG_HAS_OCSPRESPHASH	8
#define NETCA_PKI_CRLOCSPREF_FLAG_FINISH			0x100


#define NETCA_PKI_GET_USER_CERT_TYPE_ENCRYPT	1
#define NETCA_PKI_GET_USER_CERT_TYPE_SIGN		2


#define NETCA_PKI_DEVICE_EVENT_TYPE_CHANGE_PWD	0x11
#define NETCA_PKI_DEVICE_EVENT_TYPE_UNLOCK_PWD	0x12
#define NETCA_PKI_DEVICE_EVENT_TYPE_CREATE_DATA	0x13
#define NETCA_PKI_DEVICE_EVENT_TYPE_WRITE_DATA	0x14
#define NETCA_PKI_DEVICE_EVENT_TYPE_DELETE_DATA	0x15
#define NETCA_PKI_DEVICE_EVENT_TYPE_GENERATE_KEYPAIR	0x16
#define NETCA_PKI_DEVICE_EVENT_TYPE_IMPORT_KEYPAIR	0x17
#define NETCA_PKI_DEVICE_EVENT_TYPE_DELETE_KEYPAIR	0x18
#define NETCA_PKI_DEVICE_EVENT_TYPE_DELETE_CERT	0x19
#define NETCA_PKI_DEVICE_EVENT_TYPE_WRITE_CERT	0x1A


#define NETCA_PKI_TLS_VERIFY_FLAG_NONE			1
#define NETCA_PKI_TLS_VERIFY_FLAG_NO_REVOKE		8
#define NETCA_PKI_TLS_VERIFY_FLAG_ALL			16

/* 正常使用状态 */
#define NETCA_PKI_DEVICE_STATE_NORMAL				0
/* 未格式化状态 */
#define NETCA_PKI_DEVICE_STATE_UNINITIALIZED		1
/* 其他CA的Key */
#define NETCA_PKI_DEVICE_STATE_OTHER				2


#define NETCA_PKI_REVOKE_INFO_SOURCE_TYPE_CRL	1
#define NETCA_PKI_REVOKE_INFO_SOURCE_TYPE_OCSP	2


/*
 *	JWS紧凑序列化
 */
#define NETCA_PKI_JWS_TYPE_COMPACT_SERIALIZATION		1
/*
 *	JWS JSON 序列化
 */
#define NETCA_PKI_JWS_TYPE_JSON_SERIALIZATION			2

/* 签名 */
#define NETCA_PKI_JWS_TYPE_SIGN		1
/* MAC */
#define NETCA_PKI_JWS_TYPE_MAC		2


/* 不带签名原文 */	
#define NETCA_PKI_JWS_FLAG_DETACHED						1
/* 有效载荷不编码 */
#define NETCA_PKI_JWS_FLAG_USE_UNENCODED_PAYLOAD		2

/*
 *	不包含证书相关的头
 */
#define NETCA_PKI_JOSE_CERTID_TYPE_NONE				0
/*
 *	X.509 Certificate Chain，至少包含签名证书，尽量包括整个证书链（包括根），但不保证
 */
#define NETCA_PKI_JOSE_CERTID_TYPE_X5C				1
/*
 *	X.509 Certificate Chain,仅包括签名证书
 */
#define NETCA_PKI_JOSE_CERTID_TYPE_X5C_ONLY_CERT		2
/*
 *	X.509 Certificate SHA-1 Thumbprint
 */
#define NETCA_PKI_JOSE_CERTID_TYPE_X5T				3
/*
 *	X.509 Certificate SHA-256 Thumbprint
 */
#define NETCA_PKI_JOSE_CERTID_TYPE_X5T_S256			4


/*
 *	JWE紧凑序列化
 */
#define NETCA_PKI_JWE_TYPE_COMPACT_SERIALIZATION		1
/*
 *	JWE JSON 序列化
 */
#define NETCA_PKI_JWE_TYPE_JSON_SERIALIZATION			2

/*
 *	A128CBC-HS256
 */
#define NETCA_PKI_JWE_CONTENT_ENC_ALGO_AES_128_CBC_HMAC_SHA_256		1
/*
 *	A192CBC-HS384
 */
#define NETCA_PKI_JWE_CONTENT_ENC_ALGO_AES_192_CBC_HMAC_SHA_384		2
/*
 *	A256CBC-HS512
 */
#define NETCA_PKI_JWE_CONTENT_ENC_ALGO_AES_256_CBC_HMAC_SHA_512		3
/*
 *	A128GCM
 */
#define NETCA_PKI_JWE_CONTENT_ENC_ALGO_AES_128_GCM					4
/*
 *	A192GCM
 */
#define NETCA_PKI_JWE_CONTENT_ENC_ALGO_AES_192_GCM					5
/*
 *	A256GCM
 */
#define NETCA_PKI_JWE_CONTENT_ENC_ALGO_AES_256_GCM					6
/*
 *	SM4CBC-HSM3
 */
#define NETCA_PKI_JWE_CONTENT_ENC_ALGO_SM4_CBC_HMAC_SM3				7


/*
 *	RSAES-PKCS1-v1_5
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_RSA1_5						1
/*
 *	RSAES OAEP using default parameter
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_RSA_OAEP						2
/*
 *	RSAES OAEP using SHA-256 and MGF1 with SHA-256
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_RSA_OAEP_256					3
/*
 *	A128KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_AES_128_KEYWRAP				4
/*
 *	A192KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_AES_192_KEYWRAP				5
/*
 *	A256KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_AES_256_KEYWRAP				6
/*
 *	dir
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_DIR							7
/*
 *	ECDH-ES
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_ECDH_ES						8
/*
 *	ECDH-ES+A128KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_ECDH_ES_AES_128_KEYWRAP		9
/*
 *	ECDH-ES+A192KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_ECDH_ES_AES_192_KEYWRAP		10
/*
 *	ECDH-ES+A256KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_ECDH_ES_AES_256_KEYWRAP		11
/*
 *	A128GCMKW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_AES_128_GCM_KEYWRAP			12
/*
 *	A192GCMKW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_AES_192_GCM_KEYWRAP			13
/*
 *	A256GCMKW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_AES_256_GCM_KEYWRAP			14
/*
 *	PBES2-HS256+A128KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_PBES2_HMAC_SHA256_AES_128_KEYWRAP			15
/*
 *	PBES2-HS384+A192KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_PBES2_HMAC_SHA384_AES_192_KEYWRAP			16
/*
 *	PBES2-HS512+A256KW
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_PBES2_HMAC_SHA512_AES_256_KEYWRAP			17
/*
 *	SM2加密
 */
#define NETCA_PKI_JWE_ENCRYPT_CEK_ALGO_SM2_ENCRYPT									18


/*
 *	签名类型的JWT
 */
#define NETCA_PKI_JWT_TYPE_JWS		1
/*
 *	加密类型的JWT
 */
#define NETCA_PKI_JWT_TYPE_JWE		2



#define NETCA_PKI_JWT_CLAIM_NAME_ISSUER				"iss"
#define NETCA_PKI_JWT_CLAIM_NAME_SUBJECT			"sub"
#define NETCA_PKI_JWT_CLAIM_NAME_AUDIENCE			"aud"
#define NETCA_PKI_JWT_CLAIM_NAME_EXPIRATION_TIME	"exp"
#define NETCA_PKI_JWT_CLAIM_NAME_NOT_BEFORE			"nbf"
#define NETCA_PKI_JWT_CLAIM_NAME_ISSUED_AT			"iat"
#define NETCA_PKI_JWT_CLAIM_NAME_JWT_ID				"jti"


#define NETCA_PKI_PKCS8_ENCODE_FLAG_USE_GM_SM2_PRIVKEY		1

#define NETCA_PKI_PKCS8_DECODE_FLAG_ONLY_GM_SM2_PRIVKEY		0x80
#define NETCA_PKI_PKCS8_DECODE_FLAG_ONLY_EC_PRIVKEY			0x100

#define NETCA_PKI_PKCS8_ENCRYPT_ALGORITHM_TDESCBC		1
#define NETCA_PKI_PKCS8_ENCRYPT_ALGORITHM_AES128CBC		2
#define NETCA_PKI_PKCS8_ENCRYPT_ALGORITHM_AES192CBC		3
#define NETCA_PKI_PKCS8_ENCRYPT_ALGORITHM_AES256CBC		4
#define NETCA_PKI_PKCS8_ENCRYPT_ALGORITHM_SM4CBC		5


#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_ENC_ALGORITHM_AES128CBC		1
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_ENC_ALGORITHM_AES192CBC		2
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_ENC_ALGORITHM_AES256CBC		3
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_ENC_ALGORITHM_SM4CBC		4

#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_INCLUDE_CERT_OPTION_NONE	1
#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_INCLUDE_CERT_OPTION_SELF	2

#define NETCA_PKI_SIGNED_AND_ENVELOPED_DATA_RECIPENTID_ISSUER_AND_SERIALNUMBER		1

#define NETCA_PKI_ENCRYPTED_DATA_FLAG_USE_Q7            1
#define NETCA_PKI_ENCRYPTED_DATA_FLAG_NO_CONTENT_INFO   2

#define NETCA_PKI_ENCRYPTED_DATA_ALGORITHM_TDESCBC		1
#define NETCA_PKI_ENCRYPTED_DATA_ALGORITHM_AES128CBC	2
#define NETCA_PKI_ENCRYPTED_DATA_ALGORITHM_AES192CBC	3
#define NETCA_PKI_ENCRYPTED_DATA_ALGORITHM_AES256CBC	4
#define NETCA_PKI_ENCRYPTED_DATA_ALGORITHM_SM4CBC		5
#define NETCA_PKI_ENCRYPTED_DATA_ALGORITHM_SM1CBC		6
#define NETCA_PKI_ENCRYPTED_DATA_ALGORITHM_SSF33CBC		7


#define NETCA_PKI_SES_FORMAT_GMT_0031			1
#define NETCA_PKI_SES_FORMAT_GBT_38540			2

#define NETCA_PKI_SES_STAMP_CERTLIST_TYPE_CERT			1
#define NETCA_PKI_SES_STAMP_CERTLIST_TYPE_CERTDIGEST	2

#define NETCA_SCVP_WANTBACK_TYPE_CERT_PATH					1
#define NETCA_SCVP_WANTBACK_TYPE_ALL_CERT_PATHS				2
#define NETCA_SCVP_WANTBACK_TYPE_REVOCATION_INFO			4
#define NETCA_SCVP_WANTBACK_TYPE_EE_REVOCATION_INFO			8
#define NETCA_SCVP_WANTBACK_TYPE_CAS_REVOCATION_INFO		16


#define NETCA_SCVP_RESPONSE_FLAGS_FULL_REQUEST_IN_RESPONSE			1
#define NETCA_SCVP_RESPONSE_FLAGS_RESPONSE_VALIDATION_POL_BY_REF	2
#define NETCA_SCVP_RESPONSE_FLAGS_PROTECT_RESPONSE					4
#define NETCA_SCVP_RESPONSE_FLAGS_CACHED_RESPONSE					8


#define NETCA_SCVP_CERT_STATUS_GOOD				1
#define NETCA_SCVP_CERT_STATUS_CONSTRUCT_FAIL	2
#define NETCA_SCVP_CERT_STATUS_NOT_VALID		3
#define NETCA_SCVP_CERT_STATUS_NOT_VALID_NOW	4


#ifdef __cplusplus
	}	
#endif
#endif
